package rnlctl

import (
	"fmt"
	"strings"
)

func renderFishCompletion(root commandSpec) string {
	var output strings.Builder
	output.WriteString("# Generated by rnlctl. Do not edit.\n")
	writeFishHelpers(&output, root)
	output.WriteString("complete -c rnlctl -f\n")
	for _, command := range root.Commands {
		fmt.Fprintf(&output, "complete -c rnlctl -n %s -a %s -d %s\n",
			shellQuote(fishRootCommandCondition()),
			shellQuote(command.Name), shellQuote(command.Description))
	}
	fmt.Fprintf(&output, "complete -c rnlctl -n %s -s h -l help -d 'Show help'\n", shellQuote(fishRootCommandCondition()))
	fmt.Fprintf(&output, "complete -c rnlctl -n %s -l version -d 'Show version'\n", shellQuote(fishRootCommandCondition()))
	for _, option := range root.Options {
		fmt.Fprintf(&output, "complete -c rnlctl")
		if option.Short != "" {
			fmt.Fprintf(&output, " -s %s", shellQuote(option.Short))
		}
		fmt.Fprintf(&output, " -l %s -d %s\n", shellQuote(option.Long), shellQuote(option.Description))
	}
	for _, parent := range root.Commands {
		if len(parent.Commands) == 0 {
			continue
		}
		condition := fishSubcommandCondition(parent)
		for _, command := range parent.Commands {
			fmt.Fprintf(&output, "complete -c rnlctl -n %s -a %s -d %s\n",
				shellQuote(condition), shellQuote(command.Name), shellQuote(command.Description))
		}
	}
	visitCompletionCommands(root, nil, func(path []string, command commandSpec) {
		if len(path) == 0 || len(command.Commands) != 0 {
			return
		}
		for _, option := range command.Options {
			fmt.Fprintf(&output, "complete -c rnlctl -n %s", shellQuote(fishOptionCondition(path, option)))
			if option.Short != "" {
				fmt.Fprintf(&output, " -s %s", shellQuote(option.Short))
			}
			fmt.Fprintf(&output, " -l %s", shellQuote(option.Long))
			if option.Value != commandValueNone {
				output.WriteString(" -r")
			}
			switch option.Value {
			case commandValueFile:
				output.WriteString(" -F")
			case commandValueDirectory:
				output.WriteString(" -a '(__fish_complete_directories)'")
			}
			fmt.Fprintf(&output, " -d %s\n", shellQuote(option.Description))
		}
		for _, candidate := range command.Arguments {
			fmt.Fprintf(&output, "complete -c rnlctl -n %s -a %s -d %s\n",
				shellQuote(fishArgumentCondition(path, command, candidate)), shellQuote(candidate.Value), shellQuote(candidate.Description))
		}
	})
	output.WriteString("complete -c rnlctl -s h -l help -d 'Show help'\n")
	return output.String()
}

func fishSubcommandCondition(parent commandSpec) string {
	return fishPathCondition([]string{parent.Name})
}

func fishPathCondition(path []string) string {
	return "__rnlctl_completion_path_is " + shellQuote(strings.Join(path, " "))
}

func fishRootCommandCondition() string {
	return "__rnlctl_completion_path_is ''"
}

func fishOptionCondition(path []string, option commandOptionSpec) string {
	condition := fishPathCondition(path)
	if len(option.UnavailableWith) == 0 {
		return condition
	}

	arguments := make([]string, 0, len(option.UnavailableWith)+1)
	arguments = append(arguments, shellQuote(strings.Join(path, " ")))
	for _, unavailable := range option.UnavailableWith {
		arguments = append(arguments, shellQuote(unavailable))
	}
	return condition + "; and __rnlctl_completion_option_available " + strings.Join(arguments, " ")
}

func fishArgumentCondition(path []string, command commandSpec, candidate commandArgumentSpec) string {
	condition := fishPathCondition(path)
	if command.RepeatArgs {
		return condition + "; and not __rnlctl_completion_argument_used " + shellQuote(candidate.Value)
	}
	for _, option := range optionsUnavailableWithArgument(command.Options, candidate) {
		condition += "; and not __rnlctl_completion_option_used " + shellQuote("--"+option.Long)
	}
	if strings.Join(path, " ") == "logs" {
		return condition + "; and not __rnlctl_completion_logs_source_is_set"
	}

	arguments := make([]string, 0, len(command.Arguments))
	for _, argument := range command.Arguments {
		arguments = append(arguments, shellQuote(argument.Value))
	}
	return condition + "; and not __rnlctl_completion_any_argument_used " + strings.Join(arguments, " ")
}

func writeFishHelpers(output *strings.Builder, root commandSpec) {
	parents := make([]string, 0, len(root.Commands))
	for _, command := range root.Commands {
		if len(command.Commands) != 0 {
			parents = append(parents, command.Name)
		}
	}

	output.WriteString(`function __rnlctl_completion_path
  set -l tokens (commandline -opc)
  set -l command
  set -l subcommand
  for token in $tokens[2..-1]
    switch $token
      case `)
	output.WriteString(strings.Join(completionOptionPatterns(root.Options), " "))
	output.WriteString(`
        continue
    end
    if test -z "$command"
      set command $token
      continue
    end
    if test -z "$subcommand"
      switch $command
        case `)
	output.WriteString(strings.Join(parents, " "))
	output.WriteString(`
          set subcommand $token
      end
    end
  end
  if test -n "$subcommand"
    printf '%s %s\n' "$command" "$subcommand"
  else
    printf '%s\n' "$command"
  end
end

function __rnlctl_completion_path_is
  set -l path (__rnlctl_completion_path)
  test "$path" = "$argv[1]"
end

function __rnlctl_completion_argument_used
  set -l wanted (string replace -r '=.*$' '' -- $argv[1])
  for token in (commandline -opc)
    set -l actual (string replace -r '=.*$' '' -- $token)
    if test "$actual" = "$wanted"
      return 0
    end
  end
  return 1
end

function __rnlctl_completion_option_used
  set -l wanted (string replace -r '=.*$' '' -- $argv[1])
  for token in (commandline -opc)
    set -l actual (string replace -r '=.*$' '' -- $token)
    if test "$actual" = "$wanted"
      return 0
    end
  end
  return 1
end

function __rnlctl_completion_any_argument_used
  for wanted in $argv
    if __rnlctl_completion_argument_used "$wanted"
      return 0
    end
  end
  return 1
end

function __rnlctl_completion_logs_source
  set -l after_logs 0
  set -l consumes_value 0
  for token in (commandline -opc)
    if test $after_logs -eq 0
      if test "$token" = logs
        set after_logs 1
      end
      continue
    end
    switch $token
      case --quiet -q --no-color
        continue
      case --lines -n --since
        set consumes_value 1
        continue
      case '-*'
        continue
    end
    if test $consumes_value -eq 1
      set consumes_value 0
      continue
    end
    printf '%s\n' "$token"
    return 0
  end
  return 1
end

function __rnlctl_completion_logs_source_is_set
  set -l source (__rnlctl_completion_logs_source)
  test -n "$source"
end

function __rnlctl_completion_option_available
  set -l path $argv[1]
  set -e argv[1]
  if test "$path" = logs
    set -l source (__rnlctl_completion_logs_source)
    contains -- "$source" $argv
    and return 1
    return 0
  end
  not __rnlctl_completion_any_argument_used $argv
end

`)
}
