package rnlctl

import (
	"fmt"
	"strings"
)

func renderZshCompletion(root completionCommandSpec) string {
	var output strings.Builder
	output.WriteString(`#compdef rnlctl
compdef _rnlctl rnlctl

# Generated by rnlctl. Do not edit.
_rnlctl_completion_argument_used() {
  local wanted=${1%%=*} argument
  shift
  for argument in "$@"; do
    if [[ ${argument%%=*} == "$wanted" ]]; then
      return 0
    fi
  done
  return 1
}

_rnlctl() {
  local current previous command subcommand command_path token
	local -a used_arguments
	integer command_index=0 subcommand_index=0 argument_start=0 expect_value=0 i
  current=${words[CURRENT]:-}
  previous=
`)
	writeZshGlobalScan(&output, root.Options)
	writeZshDescribe(&output, "    ", "commands", "rnlctl command", append(rootCommandCandidates(root), append(optionCandidates(root.Options),
		completionCandidateSpec{Value: "--version", Description: "Show version"},
	)...))
	output.WriteString("    return\n  fi\n\n  subcommand=\n")
	for _, command := range root.Commands {
		if len(command.Commands) == 0 {
			continue
		}
		fmt.Fprintf(&output, "  if [[ $command == %s ]]; then\n", shellQuote(command.Name))
		output.WriteString("    for (( i=command_index+1; i<CURRENT; i++ )); do\n      token=${words[i]}\n      if _rnlctl_completion_is_global_option \"$token\"; then\n        continue\n      fi\n      subcommand=$token\n      subcommand_index=$i\n      break\n    done\n    if [[ -z $subcommand ]]; then\n")
		writeZshDescribe(&output, "      ", "commands", command.Name+" command", append(commandCommandCandidates(command), optionCandidates(root.Options)...))
		output.WriteString("      return\n    fi\n  fi\n")
	}
	output.WriteString("  command_path=$command\n  argument_start=$((command_index + 1))\n  if [[ -n $subcommand ]]; then\n    command_path+=\" $subcommand\"\n    argument_start=$((subcommand_index + 1))\n  fi\n\n  case $command_path in\n")
	visitCompletionCommands(root, nil, func(path []string, command completionCommandSpec) {
		if len(path) == 0 || len(command.Commands) != 0 {
			return
		}
		fmt.Fprintf(&output, "    %s)\n", shellQuote(strings.Join(path, " ")))
		writeZshOptionValues(&output, command)
		writeZshArgumentScan(&output, command)
		output.WriteString("      if [[ -z $current || $current == -* ]]; then\n")
		writeZshOptionCandidates(&output, "        ", combinedCompletionOptions(root, command))
		output.WriteString("        if [[ $current == -* ]]; then\n          return\n        fi\n      fi\n")
		if len(command.Arguments) != 0 {
			writeZshArgumentCandidates(&output, "      ", command)
		}
		output.WriteString("      return\n      ;;\n")
	})
	output.WriteString(`  esac
}

# When loaded through fpath, zsh initially executes this file as _rnlctl.
# When sourced directly, compdef above is sufficient and no completion runs.
if [[ ${funcstack[1]:-} == _rnlctl ]]; then
  _rnlctl "$@"
fi
`)
	return output.String()
}

func writeZshGlobalScan(output *strings.Builder, options []completionOptionSpec) {
	output.WriteString("  _rnlctl_completion_is_global_option() {\n    case $1 in\n      ")
	output.WriteString(strings.Join(completionOptionPatterns(options), "|"))
	output.WriteString(`) return 0 ;;
      *) return 1 ;;
    esac
  }

  command=
  for (( i=2; i<CURRENT; i++ )); do
    token=${words[i]}
    if _rnlctl_completion_is_global_option "$token"; then
      continue
    fi
    command=$token
    command_index=$i
    break
  done
  for (( i=CURRENT-1; i>1; i-- )); do
    token=${words[i]}
    if _rnlctl_completion_is_global_option "$token"; then
      continue
    fi
    previous=$token
    break
  done
  if [[ -z $command ]]; then
`)
}

func writeZshOptionValues(output *strings.Builder, command completionCommandSpec) {
	var valueOptions []completionOptionSpec
	for _, option := range command.Options {
		if option.Value != completionValueNone {
			valueOptions = append(valueOptions, option)
		}
	}
	if len(valueOptions) == 0 {
		return
	}
	output.WriteString("      case $previous in\n")
	for _, option := range valueOptions {
		patterns := []string{shellQuote("--" + option.Long)}
		if option.Short != "" {
			patterns = append(patterns, shellQuote("-"+option.Short))
		}
		fmt.Fprintf(output, "        %s)\n", strings.Join(patterns, "|"))
		switch option.Value {
		case completionValueFile:
			output.WriteString("          _files\n")
		case completionValueDirectory:
			output.WriteString("          _files -/\n")
		}
		output.WriteString("          return\n          ;;\n")
	}
	output.WriteString("      esac\n")
	for _, option := range valueOptions {
		long := "--" + option.Long + "="
		fmt.Fprintf(output, "      if [[ $current == %s* ]]; then\n", shellQuote(long))
		if option.Value == completionValueFile || option.Value == completionValueDirectory {
			output.WriteString("        compset -P '*='\n")
			if option.Value == completionValueDirectory {
				output.WriteString("        _files -/\n")
			} else {
				output.WriteString("        _files\n")
			}
		}
		output.WriteString("        return\n      fi\n")
	}
}

func writeZshArgumentScan(output *strings.Builder, command completionCommandSpec) {
	if len(command.Arguments) == 0 {
		return
	}
	valueOptions := completionValueOptions(command.Options)
	output.WriteString("      used_arguments=()\n      expect_value=0\n      for (( i=argument_start; i<CURRENT; i++ )); do\n        token=${words[i]}\n        if _rnlctl_completion_is_global_option \"$token\"; then\n          continue\n        fi\n        if (( expect_value )); then\n          expect_value=0\n          continue\n        fi\n        case $token in\n")
	if len(valueOptions) != 0 {
		fmt.Fprintf(output, "          %s)\n            expect_value=1\n            continue\n            ;;\n", strings.Join(completionOptionShellPatterns(valueOptions, false), "|"))
		fmt.Fprintf(output, "          %s)\n            continue\n            ;;\n", strings.Join(completionOptionShellPatterns(valueOptions, true), "|"))
	}
	output.WriteString("          -*)\n            continue\n            ;;\n          *)\n            used_arguments+=(\"$token\")\n            ;;\n        esac\n      done\n")
}

func writeZshOptionCandidates(output *strings.Builder, indent string, options []completionOptionSpec) {
	available := make([]completionOptionSpec, 0, len(options))
	conditional := make([]completionOptionSpec, 0, len(options))
	for _, option := range options {
		if len(option.UnavailableWith) == 0 {
			available = append(available, option)
		} else {
			conditional = append(conditional, option)
		}
	}
	output.WriteString(indent + "local -a candidates\n")
	output.WriteString(indent + "candidates=(\n")
	for _, candidate := range optionCandidates(available) {
		fmt.Fprintf(output, "%s  %s\n", indent, shellQuote(candidate.Value+":"+candidate.Description))
	}
	output.WriteString(indent + ")\n")
	for _, option := range conditional {
		fmt.Fprintf(output, "%sif %s; then\n", indent, zshOptionAvailableCondition(option))
		for _, candidate := range completionOptionCandidates(option) {
			fmt.Fprintf(output, "%s  candidates+=(%s)\n", indent, shellQuote(candidate.Value+":"+candidate.Description))
		}
		output.WriteString(indent + "fi\n")
	}
	fmt.Fprintf(output, "%s_describe -t options %s candidates\n", indent, shellQuote("option"))
}

func writeZshArgumentCandidates(output *strings.Builder, indent string, command completionCommandSpec) {
	if !command.RepeatArgs {
		fmt.Fprintf(output, "%sif (( ${#used_arguments} == 0 )); then\n", indent)
		writeZshCandidateValues(output, indent+"  ", command.Arguments)
		output.WriteString(indent + "fi\n")
		return
	}
	if hasNoSpaceCandidate(command.Arguments) {
		for _, candidate := range command.Arguments {
			fmt.Fprintf(output, "%sif ! _rnlctl_completion_argument_used %s \"${used_arguments[@]}\"; then\n", indent, shellQuote(candidate.Value))
			fmt.Fprintf(output, "%s  compadd -S '' -- %s\n", indent, shellQuote(candidate.Value))
			output.WriteString(indent + "fi\n")
		}
		return
	}
	output.WriteString(indent + "local -a candidates\n")
	output.WriteString(indent + "candidates=()\n")
	for _, candidate := range command.Arguments {
		fmt.Fprintf(output, "%sif ! _rnlctl_completion_argument_used %s \"${used_arguments[@]}\"; then\n", indent, shellQuote(candidate.Value))
		fmt.Fprintf(output, "%s  candidates+=(%s)\n", indent, shellQuote(candidate.Value+":"+candidate.Description))
		output.WriteString(indent + "fi\n")
	}
	output.WriteString(indent + "(( ${#candidates} > 0 )) && _describe -t values 'value' candidates\n")
}

func writeZshCandidateValues(output *strings.Builder, indent string, candidates []completionCandidateSpec) {
	if hasNoSpaceCandidate(candidates) {
		output.WriteString(indent + "compadd -S '' --")
		for _, candidate := range candidates {
			output.WriteByte(' ')
			output.WriteString(shellQuote(candidate.Value))
		}
		output.WriteByte('\n')
		return
	}
	writeZshDescribe(output, indent, "values", "value", candidates)
}

func zshOptionAvailableCondition(option completionOptionSpec) string {
	conditions := make([]string, 0, len(option.UnavailableWith))
	for _, argument := range option.UnavailableWith {
		conditions = append(conditions, "! _rnlctl_completion_argument_used "+shellQuote(argument)+" \"${used_arguments[@]}\"")
	}
	return strings.Join(conditions, " && ")
}

func writeZshDescribe(output *strings.Builder, indent, tag, label string, candidates []completionCandidateSpec) {
	output.WriteString(indent + "local -a candidates\n")
	output.WriteString(indent + "candidates=(\n")
	for _, candidate := range candidates {
		fmt.Fprintf(output, "%s  %s\n", indent, shellQuote(candidate.Value+":"+candidate.Description))
	}
	output.WriteString(indent + ")\n")
	fmt.Fprintf(output, "%s_describe -t %s %s candidates\n", indent, tag, shellQuote(label))
}
