package rnlctl

import (
	"fmt"
	"strings"
)

func renderBashCompletion(root commandSpec) string {
	var output strings.Builder
	output.WriteString(`# Generated by rnlctl. Do not edit.
_rnlctl_completion_words() {
  local current=$1 candidate
  shift
  for candidate in "$@"; do
    if [[ $candidate == "$current"* ]]; then
      COMPREPLY+=("$candidate")
    fi
  done
}

_rnlctl_completion_path() {
  local current=$1 prefix=$2 directories=$3 candidate
  if [[ $directories == 1 ]]; then
    while IFS= read -r candidate; do
      COMPREPLY+=("${prefix}${candidate}")
    done < <(compgen -d -- "$current")
  else
    while IFS= read -r candidate; do
      COMPREPLY+=("${prefix}${candidate}")
    done < <(compgen -f -- "$current")
  fi
  compopt -o filenames 2>/dev/null || true
}

_rnlctl_completion_argument_used() {
  local wanted=${1%%=*} argument
  shift
  for argument in "$@"; do
    if [[ ${argument%%=*} == "$wanted" ]]; then
      return 0
    fi
  done
  return 1
}

_rnlctl_completion() {
  local current previous command subcommand path token
  local -a used_arguments=() used_options=()
  local -i command_index=0 subcommand_index=0 argument_start=0 expect_value=0 i
  COMPREPLY=()
  current=${COMP_WORDS[COMP_CWORD]:-}
  previous=
`)
	writeBashGlobalOptionValues(&output, root.Options)
	writeBashGlobalScan(&output, root.Options)
	writeBashCandidates(&output, "    ", append(rootCommandCandidates(root), append(optionCandidates(root.Options),
		commandArgumentSpec{Value: "--version", Description: "Show version"},
	)...))
	output.WriteString("    return\n  fi\n\n  subcommand=\n")
	for _, command := range root.Commands {
		if len(command.Commands) == 0 {
			continue
		}
		fmt.Fprintf(&output, "  if [[ $command == %s ]]; then\n", shellQuote(command.Name))
		output.WriteString("    expect_value=0\n    for (( i=command_index+1; i<COMP_CWORD; i++ )); do\n      token=${COMP_WORDS[i]}\n      if (( expect_value )); then\n        if [[ $token == = ]]; then\n          continue\n        fi\n        expect_value=0\n        continue\n      fi\n      if _rnlctl_completion_is_global_option \"$token\"; then\n        if _rnlctl_completion_global_option_takes_value \"$token\"; then\n          expect_value=1\n        fi\n        continue\n      fi\n      subcommand=$token\n      subcommand_index=$i\n      break\n    done\n    if [[ -z $subcommand ]]; then\n")
		writeBashCandidates(&output, "      ", append(commandCommandCandidates(command), optionCandidates(root.Options)...))
		output.WriteString("      return\n    fi\n  fi\n")
	}
	output.WriteString("  path=$command\n  argument_start=$((command_index + 1))\n  if [[ -n $subcommand ]]; then\n    path+=\" $subcommand\"\n    argument_start=$((subcommand_index + 1))\n  fi\n\n  case $path in\n")
	visitCompletionCommands(root, nil, func(path []string, command commandSpec) {
		if len(path) == 0 || len(command.Commands) != 0 {
			return
		}
		fmt.Fprintf(&output, "    %s)\n", shellQuote(strings.Join(path, " ")))
		writeBashOptionValues(&output, command)
		writeBashArgumentScan(&output, command)
		output.WriteString("      if [[ -z $current || $current == -* ]]; then\n")
		writeBashOptionCandidates(&output, "        ", combinedCompletionOptions(root, command))
		output.WriteString("        if [[ $current == -* ]]; then\n          return\n        fi\n      fi\n")
		if len(command.Arguments) != 0 {
			writeBashArgumentCandidates(&output, "      ", command)
			if hasNoSpaceCandidate(command.Arguments) {
				output.WriteString("      compopt -o nospace 2>/dev/null || true\n")
			}
		}
		output.WriteString("      return\n      ;;\n")
	})
	output.WriteString(`  esac
}

complete -F _rnlctl_completion rnlctl
`)
	return output.String()
}

func writeBashGlobalScan(output *strings.Builder, options []commandOptionSpec) {
	output.WriteString("  _rnlctl_completion_is_global_option() {\n    case $1 in\n      ")
	output.WriteString(strings.Join(completionOptionPatterns(options), "|"))
	output.WriteString(`) return 0 ;;
      *) return 1 ;;
    esac
  }

  _rnlctl_completion_global_option_takes_value() {
    case $1 in
      `)
	valuePatterns := completionOptionShellPatterns(completionValueOptions(options), false)
	if len(valuePatterns) == 0 {
		output.WriteString("__rnlctl_no_global_value_options__")
	} else {
		output.WriteString(strings.Join(valuePatterns, "|"))
	}
	output.WriteString(`) return 0 ;;
      *) return 1 ;;
    esac
  }

  command=
  expect_value=0
  for (( i=1; i<COMP_CWORD; i++ )); do
    token=${COMP_WORDS[i]}
    if (( expect_value )); then
      if [[ $token == = ]]; then
        continue
      fi
      expect_value=0
      continue
    fi
    if _rnlctl_completion_is_global_option "$token"; then
      if _rnlctl_completion_global_option_takes_value "$token"; then
        expect_value=1
      fi
      continue
    fi
    command=$token
    command_index=$i
    break
  done
  for (( i=COMP_CWORD-1; i>0; i-- )); do
    token=${COMP_WORDS[i]}
    if _rnlctl_completion_is_global_option "$token"; then
      continue
    fi
    if (( i > 1 )) && _rnlctl_completion_global_option_takes_value "${COMP_WORDS[i-1]}"; then
      (( i-- ))
      continue
    fi
    if (( i > 2 )) && [[ ${COMP_WORDS[i-1]} == = ]] && _rnlctl_completion_global_option_takes_value "${COMP_WORDS[i-2]}"; then
      (( i-=2 ))
      continue
    fi
    previous=$token
    break
  done
  if [[ -z $command ]]; then
`)
}

func writeBashGlobalOptionValues(output *strings.Builder, options []commandOptionSpec) {
	valueOptions := completionValueOptions(options)
	if len(valueOptions) == 0 {
		return
	}
	output.WriteString("  case ${COMP_WORDS[COMP_CWORD-1]:-} in\n")
	for _, option := range valueOptions {
		patterns := []string{shellQuote("--" + option.Long)}
		if option.Short != "" {
			patterns = append(patterns, shellQuote("-"+option.Short))
		}
		fmt.Fprintf(output, "    %s)\n", strings.Join(patterns, "|"))
		writeBashOptionValueAction(output, "      ", option, "", false)
		output.WriteString("      return\n      ;;\n")
	}
	output.WriteString("  esac\n  if [[ ${COMP_WORDS[COMP_CWORD-1]:-} == = && $COMP_CWORD -ge 2 ]]; then\n    case ${COMP_WORDS[COMP_CWORD-2]} in\n")
	for _, option := range valueOptions {
		patterns := []string{shellQuote("--" + option.Long)}
		if option.Short != "" {
			patterns = append(patterns, shellQuote("-"+option.Short))
		}
		fmt.Fprintf(output, "      %s)\n", strings.Join(patterns, "|"))
		writeBashOptionValueAction(output, "        ", option, "", false)
		output.WriteString("        return\n        ;;\n")
	}
	output.WriteString("    esac\n  fi\n  case $current in\n")
	for _, option := range valueOptions {
		for _, name := range completionOptionNames(option) {
			prefix := name + "="
			fmt.Fprintf(output, "    %s*)\n", shellQuote(prefix))
			writeBashOptionValueAction(output, "      ", option, prefix, true)
			output.WriteString("      return\n      ;;\n")
		}
	}
	output.WriteString("  esac\n")
}

func writeBashOptionValues(output *strings.Builder, command commandSpec) {
	valueOptions := completionValueOptions(command.Options)
	if len(valueOptions) == 0 {
		return
	}
	output.WriteString("      case $previous in\n")
	for _, option := range valueOptions {
		patterns := []string{shellQuote("--" + option.Long)}
		if option.Short != "" {
			patterns = append(patterns, shellQuote("-"+option.Short))
		}
		fmt.Fprintf(output, "        %s)\n", strings.Join(patterns, "|"))
		writeBashOptionValueAction(output, "          ", option, "", false)
		output.WriteString("          return\n          ;;\n")
	}
	output.WriteString("      esac\n      if [[ $previous == = && $COMP_CWORD -ge 2 ]]; then\n        case ${COMP_WORDS[COMP_CWORD-2]} in\n")
	for _, option := range valueOptions {
		patterns := []string{shellQuote("--" + option.Long)}
		if option.Short != "" {
			patterns = append(patterns, shellQuote("-"+option.Short))
		}
		fmt.Fprintf(output, "          %s)\n", strings.Join(patterns, "|"))
		writeBashOptionValueAction(output, "            ", option, "", false)
		output.WriteString("            return\n            ;;\n")
	}
	output.WriteString("        esac\n      fi\n      case $current in\n")
	for _, option := range valueOptions {
		for _, name := range completionOptionNames(option) {
			prefix := name + "="
			fmt.Fprintf(output, "        %s*)\n", shellQuote(prefix))
			writeBashOptionValueAction(output, "          ", option, prefix, true)
			output.WriteString("          return\n          ;;\n")
		}
	}
	output.WriteString("      esac\n")
}

func writeBashOptionValueAction(output *strings.Builder, indent string, option commandOptionSpec, prefix string, inline bool) {
	if len(option.ValueCandidates) != 0 {
		writeBashCandidates(output, indent, completionOptionValueCandidates(option, prefix))
		return
	}
	current := "\"$current\""
	if inline {
		current = fmt.Sprintf("\"${current#%s}\"", prefix)
	}
	switch option.Value {
	case commandValueFile:
		fmt.Fprintf(output, "%s_rnlctl_completion_path %s %s 0\n", indent, current, shellQuote(prefix))
	case commandValueDirectory:
		fmt.Fprintf(output, "%s_rnlctl_completion_path %s %s 1\n", indent, current, shellQuote(prefix))
	}
}

func writeBashArgumentScan(output *strings.Builder, command commandSpec) {
	if len(command.Arguments) == 0 {
		return
	}
	output.WriteString("      used_arguments=()\n      used_options=()\n      expect_value=0\n      for (( i=argument_start; i<COMP_CWORD; i++ )); do\n        token=${COMP_WORDS[i]}\n        if (( expect_value )); then\n          if [[ $token == = ]]; then\n            continue\n          fi\n          expect_value=0\n          continue\n        fi\n        if _rnlctl_completion_is_global_option \"$token\"; then\n          if _rnlctl_completion_global_option_takes_value \"$token\"; then\n            expect_value=1\n          fi\n          continue\n        fi\n        case $token in\n")
	for _, option := range command.Options {
		patterns := completionOptionShellPatterns([]commandOptionSpec{option}, false)
		fmt.Fprintf(output, "          %s)\n            used_options+=(%s)\n", strings.Join(patterns, "|"), shellQuote("--"+option.Long))
		if option.Value != commandValueNone {
			output.WriteString("            expect_value=1\n")
		}
		output.WriteString("            continue\n            ;;\n")
		if option.Value == commandValueNone {
			continue
		}
		inlinePatterns := completionOptionShellPatterns([]commandOptionSpec{option}, true)
		fmt.Fprintf(output, "          %s)\n            used_options+=(%s)\n            continue\n            ;;\n", strings.Join(inlinePatterns, "|"), shellQuote("--"+option.Long))
	}
	output.WriteString("          -*)\n            continue\n            ;;\n          *)\n            used_arguments+=(\"$token\")\n            ;;\n        esac\n      done\n")
}

func writeBashOptionCandidates(output *strings.Builder, indent string, options []commandOptionSpec) {
	available := make([]commandOptionSpec, 0, len(options))
	for _, option := range options {
		if len(option.UnavailableWith) == 0 {
			available = append(available, option)
		}
	}
	writeBashCandidates(output, indent, optionCandidates(available))
	for _, option := range options {
		if len(option.UnavailableWith) == 0 {
			continue
		}
		fmt.Fprintf(output, "%sif %s; then\n", indent, bashOptionAvailableCondition(option))
		writeBashCandidates(output, indent+"  ", completionOptionCandidates(option))
		output.WriteString(indent + "fi\n")
	}
}

func writeBashArgumentCandidates(output *strings.Builder, indent string, command commandSpec) {
	if !command.RepeatArgs {
		fmt.Fprintf(output, "%sif (( ${#used_arguments[@]} == 0 )); then\n", indent)
		for _, candidate := range command.Arguments {
			condition := bashArgumentAvailableCondition(command, candidate)
			if condition != "" {
				fmt.Fprintf(output, "%s  if %s; then\n", indent, condition)
				writeBashCandidates(output, indent+"    ", []commandArgumentSpec{candidate})
				output.WriteString(indent + "  fi\n")
				continue
			}
			writeBashCandidates(output, indent+"  ", []commandArgumentSpec{candidate})
		}
		output.WriteString(indent + "fi\n")
		return
	}
	for _, candidate := range command.Arguments {
		conditions := []string{"! _rnlctl_completion_argument_used " + shellQuote(candidate.Value) + " \"${used_arguments[@]}\""}
		if condition := bashArgumentAvailableCondition(command, candidate); condition != "" {
			conditions = append(conditions, condition)
		}
		fmt.Fprintf(output, "%sif %s; then\n", indent, strings.Join(conditions, " && "))
		writeBashCandidates(output, indent+"  ", []commandArgumentSpec{candidate})
		output.WriteString(indent + "fi\n")
	}
}

func bashArgumentAvailableCondition(command commandSpec, candidate commandArgumentSpec) string {
	options := optionsUnavailableWithArgument(command.Options, candidate)
	conditions := make([]string, 0, len(options))
	for _, option := range options {
		conditions = append(conditions, "! _rnlctl_completion_argument_used "+shellQuote("--"+option.Long)+" \"${used_options[@]}\"")
	}
	return strings.Join(conditions, " && ")
}

func bashOptionAvailableCondition(option commandOptionSpec) string {
	conditions := make([]string, 0, len(option.UnavailableWith))
	for _, argument := range option.UnavailableWith {
		conditions = append(conditions, "! _rnlctl_completion_argument_used "+shellQuote(argument)+" \"${used_arguments[@]}\"")
	}
	return strings.Join(conditions, " && ")
}

func writeBashCandidates(output *strings.Builder, indent string, candidates []commandArgumentSpec) {
	output.WriteString(indent + "_rnlctl_completion_words \"$current\"")
	for _, candidate := range candidates {
		output.WriteByte(' ')
		output.WriteString(shellQuote(candidate.Value))
	}
	output.WriteByte('\n')
}
