package rnlctl

import (
	"fmt"
	"strings"
)

func renderBashCompletion(root commandSpec) string {
	var output strings.Builder
	output.WriteString(`# Generated by rnlctl. Do not edit.
_rnlctl_completion_words() {
  local current=$1 candidate
  shift
  for candidate in "$@"; do
    if [[ $candidate == "$current"* ]]; then
      COMPREPLY+=("$candidate")
    fi
  done
}

_rnlctl_completion_path() {
  local current=$1 prefix=$2 directories=$3 candidate
  if [[ $directories == 1 ]]; then
    while IFS= read -r candidate; do
      COMPREPLY+=("${prefix}${candidate}")
    done < <(compgen -d -- "$current")
  else
    while IFS= read -r candidate; do
      COMPREPLY+=("${prefix}${candidate}")
    done < <(compgen -f -- "$current")
  fi
  compopt -o filenames 2>/dev/null || true
}

_rnlctl_completion_argument_used() {
  local wanted=${1%%=*} argument
  shift
  for argument in "$@"; do
    if [[ ${argument%%=*} == "$wanted" ]]; then
      return 0
    fi
  done
  return 1
}

_rnlctl_completion() {
  local current previous command subcommand path token
	local -a used_arguments=()
	local -i command_index=0 subcommand_index=0 argument_start=0 expect_value=0 i
  COMPREPLY=()
  current=${COMP_WORDS[COMP_CWORD]:-}
  previous=
`)
	writeBashGlobalScan(&output, root.Options)
	writeBashCandidates(&output, "    ", append(rootCommandCandidates(root), append(optionCandidates(root.Options),
		commandArgumentSpec{Value: "--version", Description: "Show version"},
	)...))
	output.WriteString("    return\n  fi\n\n  subcommand=\n")
	for _, command := range root.Commands {
		if len(command.Commands) == 0 {
			continue
		}
		fmt.Fprintf(&output, "  if [[ $command == %s ]]; then\n", shellQuote(command.Name))
		output.WriteString("    for (( i=command_index+1; i<COMP_CWORD; i++ )); do\n      token=${COMP_WORDS[i]}\n      if _rnlctl_completion_is_global_option \"$token\"; then\n        continue\n      fi\n      subcommand=$token\n      subcommand_index=$i\n      break\n    done\n    if [[ -z $subcommand ]]; then\n")
		writeBashCandidates(&output, "      ", append(commandCommandCandidates(command), optionCandidates(root.Options)...))
		output.WriteString("      return\n    fi\n  fi\n")
	}
	output.WriteString("  path=$command\n  argument_start=$((command_index + 1))\n  if [[ -n $subcommand ]]; then\n    path+=\" $subcommand\"\n    argument_start=$((subcommand_index + 1))\n  fi\n\n  case $path in\n")
	visitCompletionCommands(root, nil, func(path []string, command commandSpec) {
		if len(path) == 0 || len(command.Commands) != 0 {
			return
		}
		fmt.Fprintf(&output, "    %s)\n", shellQuote(strings.Join(path, " ")))
		writeBashOptionValues(&output, command)
		writeBashArgumentScan(&output, command)
		output.WriteString("      if [[ -z $current || $current == -* ]]; then\n")
		writeBashOptionCandidates(&output, "        ", combinedCompletionOptions(root, command))
		output.WriteString("        if [[ $current == -* ]]; then\n          return\n        fi\n      fi\n")
		if len(command.Arguments) != 0 {
			writeBashArgumentCandidates(&output, "      ", command)
			if hasNoSpaceCandidate(command.Arguments) {
				output.WriteString("      compopt -o nospace 2>/dev/null || true\n")
			}
		}
		output.WriteString("      return\n      ;;\n")
	})
	output.WriteString(`  esac
}

complete -F _rnlctl_completion rnlctl
`)
	return output.String()
}

func writeBashGlobalScan(output *strings.Builder, options []commandOptionSpec) {
	output.WriteString("  _rnlctl_completion_is_global_option() {\n    case $1 in\n      ")
	output.WriteString(strings.Join(completionOptionPatterns(options), "|"))
	output.WriteString(`) return 0 ;;
      *) return 1 ;;
    esac
  }

  command=
  for (( i=1; i<COMP_CWORD; i++ )); do
    token=${COMP_WORDS[i]}
    if _rnlctl_completion_is_global_option "$token"; then
      continue
    fi
    command=$token
    command_index=$i
    break
  done
  for (( i=COMP_CWORD-1; i>0; i-- )); do
    token=${COMP_WORDS[i]}
    if _rnlctl_completion_is_global_option "$token"; then
      continue
    fi
    previous=$token
    break
  done
  if [[ -z $command ]]; then
`)
}

func writeBashOptionValues(output *strings.Builder, command commandSpec) {
	var valueOptions []commandOptionSpec
	for _, option := range command.Options {
		if option.Value != commandValueNone {
			valueOptions = append(valueOptions, option)
		}
	}
	if len(valueOptions) == 0 {
		return
	}
	output.WriteString("      case $previous in\n")
	for _, option := range valueOptions {
		patterns := []string{shellQuote("--" + option.Long)}
		if option.Short != "" {
			patterns = append(patterns, shellQuote("-"+option.Short))
		}
		fmt.Fprintf(output, "        %s)\n", strings.Join(patterns, "|"))
		switch option.Value {
		case commandValueFile:
			output.WriteString("          _rnlctl_completion_path \"$current\" \"\" 0\n")
		case commandValueDirectory:
			output.WriteString("          _rnlctl_completion_path \"$current\" \"\" 1\n")
		}
		output.WriteString("          return\n          ;;\n")
	}
	output.WriteString("      esac\n      if [[ $previous == = && $COMP_CWORD -ge 2 ]]; then\n        case ${COMP_WORDS[COMP_CWORD-2]} in\n")
	for _, option := range valueOptions {
		patterns := []string{shellQuote("--" + option.Long)}
		if option.Short != "" {
			patterns = append(patterns, shellQuote("-"+option.Short))
		}
		fmt.Fprintf(output, "          %s)\n", strings.Join(patterns, "|"))
		switch option.Value {
		case commandValueFile:
			output.WriteString("            _rnlctl_completion_path \"$current\" \"\" 0\n")
		case commandValueDirectory:
			output.WriteString("            _rnlctl_completion_path \"$current\" \"\" 1\n")
		}
		output.WriteString("            return\n            ;;\n")
	}
	output.WriteString("        esac\n      fi\n      case $current in\n")
	for _, option := range valueOptions {
		long := "--" + option.Long + "="
		fmt.Fprintf(output, "        %s*)\n", shellQuote(long))
		switch option.Value {
		case commandValueFile:
			fmt.Fprintf(output, "          _rnlctl_completion_path \"${current#%s}\" %s 0\n", long, shellQuote(long))
		case commandValueDirectory:
			fmt.Fprintf(output, "          _rnlctl_completion_path \"${current#%s}\" %s 1\n", long, shellQuote(long))
		}
		output.WriteString("          return\n          ;;\n")
	}
	output.WriteString("      esac\n")
}

func writeBashArgumentScan(output *strings.Builder, command commandSpec) {
	if len(command.Arguments) == 0 {
		return
	}
	valueOptions := completionValueOptions(command.Options)
	output.WriteString("      used_arguments=()\n      expect_value=0\n      for (( i=argument_start; i<COMP_CWORD; i++ )); do\n        token=${COMP_WORDS[i]}\n        if _rnlctl_completion_is_global_option \"$token\"; then\n          continue\n        fi\n        if (( expect_value )); then\n          if [[ $token == = ]]; then\n            continue\n          fi\n          expect_value=0\n          continue\n        fi\n        case $token in\n")
	if len(valueOptions) != 0 {
		fmt.Fprintf(output, "          %s)\n            expect_value=1\n            continue\n            ;;\n", strings.Join(completionOptionShellPatterns(valueOptions, false), "|"))
		fmt.Fprintf(output, "          %s)\n            continue\n            ;;\n", strings.Join(completionOptionShellPatterns(valueOptions, true), "|"))
	}
	output.WriteString("          -*)\n            continue\n            ;;\n          *)\n            used_arguments+=(\"$token\")\n            ;;\n        esac\n      done\n")
}

func writeBashOptionCandidates(output *strings.Builder, indent string, options []commandOptionSpec) {
	available := make([]commandOptionSpec, 0, len(options))
	for _, option := range options {
		if len(option.UnavailableWith) == 0 {
			available = append(available, option)
		}
	}
	writeBashCandidates(output, indent, optionCandidates(available))
	for _, option := range options {
		if len(option.UnavailableWith) == 0 {
			continue
		}
		fmt.Fprintf(output, "%sif %s; then\n", indent, bashOptionAvailableCondition(option))
		writeBashCandidates(output, indent+"  ", completionOptionCandidates(option))
		output.WriteString(indent + "fi\n")
	}
}

func writeBashArgumentCandidates(output *strings.Builder, indent string, command commandSpec) {
	if !command.RepeatArgs {
		fmt.Fprintf(output, "%sif (( ${#used_arguments[@]} == 0 )); then\n", indent)
		writeBashCandidates(output, indent+"  ", command.Arguments)
		output.WriteString(indent + "fi\n")
		return
	}
	for _, candidate := range command.Arguments {
		fmt.Fprintf(output, "%sif ! _rnlctl_completion_argument_used %s \"${used_arguments[@]}\"; then\n", indent, shellQuote(candidate.Value))
		writeBashCandidates(output, indent+"  ", []commandArgumentSpec{candidate})
		output.WriteString(indent + "fi\n")
	}
}

func bashOptionAvailableCondition(option commandOptionSpec) string {
	conditions := make([]string, 0, len(option.UnavailableWith))
	for _, argument := range option.UnavailableWith {
		conditions = append(conditions, "! _rnlctl_completion_argument_used "+shellQuote(argument)+" \"${used_arguments[@]}\"")
	}
	return strings.Join(conditions, " && ")
}

func writeBashCandidates(output *strings.Builder, indent string, candidates []commandArgumentSpec) {
	output.WriteString(indent + "_rnlctl_completion_words \"$current\"")
	for _, candidate := range candidates {
		output.WriteByte(' ')
		output.WriteString(shellQuote(candidate.Value))
	}
	output.WriteByte('\n')
}
