package rnlctl

import (
	"fmt"
	"strings"
)

func renderZshCompletion(root commandSpec) string {
	var output strings.Builder
	output.WriteString(`#compdef rnlctl
compdef _rnlctl rnlctl

# Generated by rnlctl. Do not edit.
_rnlctl_completion_argument_used() {
  local wanted=${1%%=*} argument
  shift
  for argument in "$@"; do
    if [[ ${argument%%=*} == "$wanted" ]]; then
      return 0
    fi
  done
  return 1
}

_rnlctl() {
  local current previous command subcommand command_path token
  local -a used_arguments used_options
  integer command_index=0 subcommand_index=0 argument_start=0 expect_value=0 i
  current=${words[CURRENT]:-}
  previous=
`)
	writeZshGlobalOptionValues(&output, root.Options)
	writeZshGlobalScan(&output, root.Options)
	writeZshDescribe(&output, "    ", "commands", "rnlctl command", append(rootCommandCandidates(root), append(optionCandidates(root.Options),
		commandArgumentSpec{Value: "--version", Description: "Show version"},
	)...))
	output.WriteString("    return\n  fi\n\n  subcommand=\n")
	for _, command := range root.Commands {
		if len(command.Commands) == 0 {
			continue
		}
		fmt.Fprintf(&output, "  if [[ $command == %s ]]; then\n", shellQuote(command.Name))
		output.WriteString("    expect_value=0\n    for (( i=command_index+1; i<CURRENT; i++ )); do\n      token=${words[i]}\n      if (( expect_value )); then\n        expect_value=0\n        continue\n      fi\n      if _rnlctl_completion_is_global_option \"$token\"; then\n        if _rnlctl_completion_global_option_takes_value \"$token\"; then\n          expect_value=1\n        fi\n        continue\n      fi\n      subcommand=$token\n      subcommand_index=$i\n      break\n    done\n    if [[ -z $subcommand ]]; then\n")
		writeZshDescribe(&output, "      ", "commands", command.Name+" command", append(commandCommandCandidates(command), optionCandidates(root.Options)...))
		output.WriteString("      return\n    fi\n  fi\n")
	}
	output.WriteString("  command_path=$command\n  argument_start=$((command_index + 1))\n  if [[ -n $subcommand ]]; then\n    command_path+=\" $subcommand\"\n    argument_start=$((subcommand_index + 1))\n  fi\n\n  case $command_path in\n")
	visitCompletionCommands(root, nil, func(path []string, command commandSpec) {
		if len(path) == 0 || len(command.Commands) != 0 {
			return
		}
		fmt.Fprintf(&output, "    %s)\n", shellQuote(strings.Join(path, " ")))
		writeZshOptionValues(&output, command)
		writeZshArgumentScan(&output, command)
		output.WriteString("      if [[ -z $current || $current == -* ]]; then\n")
		writeZshOptionCandidates(&output, "        ", combinedCompletionOptions(root, command))
		output.WriteString("        if [[ $current == -* ]]; then\n          return\n        fi\n      fi\n")
		if len(command.Arguments) != 0 {
			writeZshArgumentCandidates(&output, "      ", command)
		}
		output.WriteString("      return\n      ;;\n")
	})
	output.WriteString(`  esac
}

# When loaded through fpath, zsh initially executes this file as _rnlctl.
# When sourced directly, compdef above is sufficient and no completion runs.
if [[ ${funcstack[1]:-} == _rnlctl ]]; then
  _rnlctl "$@"
fi
`)
	return output.String()
}

func writeZshGlobalScan(output *strings.Builder, options []commandOptionSpec) {
	output.WriteString("  _rnlctl_completion_is_global_option() {\n    case $1 in\n      ")
	output.WriteString(strings.Join(completionOptionPatterns(options), "|"))
	output.WriteString(`) return 0 ;;
      *) return 1 ;;
    esac
  }

  _rnlctl_completion_global_option_takes_value() {
    case $1 in
      `)
	valuePatterns := completionOptionShellPatterns(completionValueOptions(options), false)
	if len(valuePatterns) == 0 {
		output.WriteString("__rnlctl_no_global_value_options__")
	} else {
		output.WriteString(strings.Join(valuePatterns, "|"))
	}
	output.WriteString(`) return 0 ;;
      *) return 1 ;;
    esac
  }

  command=
  expect_value=0
  for (( i=2; i<CURRENT; i++ )); do
    token=${words[i]}
    if (( expect_value )); then
      expect_value=0
      continue
    fi
    if _rnlctl_completion_is_global_option "$token"; then
      if _rnlctl_completion_global_option_takes_value "$token"; then
        expect_value=1
      fi
      continue
    fi
    command=$token
    command_index=$i
    break
  done
  for (( i=CURRENT-1; i>1; i-- )); do
    token=${words[i]}
    if _rnlctl_completion_is_global_option "$token"; then
      continue
    fi
    if (( i > 2 )) && _rnlctl_completion_global_option_takes_value "${words[i-1]}"; then
      (( i-- ))
      continue
    fi
    previous=$token
    break
  done
  if [[ -z $command ]]; then
`)
}

func writeZshGlobalOptionValues(output *strings.Builder, options []commandOptionSpec) {
	valueOptions := completionValueOptions(options)
	if len(valueOptions) == 0 {
		return
	}
	output.WriteString("  case ${words[CURRENT-1]:-} in\n")
	for _, option := range valueOptions {
		patterns := make([]string, 0, 2)
		for _, name := range completionOptionNames(option) {
			patterns = append(patterns, shellQuote(name))
		}
		fmt.Fprintf(output, "    %s)\n", strings.Join(patterns, "|"))
		writeZshOptionValueAction(output, "      ", option, "", false)
		output.WriteString("      return\n      ;;\n")
	}
	output.WriteString("  esac\n  case $current in\n")
	for _, option := range valueOptions {
		for _, name := range completionOptionNames(option) {
			prefix := name + "="
			fmt.Fprintf(output, "    %s*)\n", shellQuote(prefix))
			writeZshOptionValueAction(output, "      ", option, prefix, true)
			output.WriteString("      return\n      ;;\n")
		}
	}
	output.WriteString("  esac\n")
}

func writeZshOptionValues(output *strings.Builder, command commandSpec) {
	valueOptions := completionValueOptions(command.Options)
	if len(valueOptions) == 0 {
		return
	}
	output.WriteString("      case $previous in\n")
	for _, option := range valueOptions {
		patterns := []string{shellQuote("--" + option.Long)}
		if option.Short != "" {
			patterns = append(patterns, shellQuote("-"+option.Short))
		}
		fmt.Fprintf(output, "        %s)\n", strings.Join(patterns, "|"))
		writeZshOptionValueAction(output, "          ", option, "", false)
		output.WriteString("          return\n          ;;\n")
	}
	output.WriteString("      esac\n")
	for _, option := range valueOptions {
		for _, name := range completionOptionNames(option) {
			prefix := name + "="
			fmt.Fprintf(output, "      if [[ $current == %s* ]]; then\n", shellQuote(prefix))
			writeZshOptionValueAction(output, "        ", option, prefix, true)
			output.WriteString("        return\n      fi\n")
		}
	}
}

func writeZshOptionValueAction(output *strings.Builder, indent string, option commandOptionSpec, prefix string, inline bool) {
	if len(option.ValueCandidates) != 0 {
		writeZshDescribe(output, indent, "values", "value", completionOptionValueCandidates(option, prefix))
		return
	}
	if inline {
		output.WriteString(indent + "compset -P '*='\n")
	}
	switch option.Value {
	case commandValueFile:
		output.WriteString(indent + "_files\n")
	case commandValueDirectory:
		output.WriteString(indent + "_files -/\n")
	}
}

func writeZshArgumentScan(output *strings.Builder, command commandSpec) {
	if len(command.Arguments) == 0 {
		return
	}
	output.WriteString("      used_arguments=()\n      used_options=()\n      expect_value=0\n      for (( i=argument_start; i<CURRENT; i++ )); do\n        token=${words[i]}\n        if (( expect_value )); then\n          expect_value=0\n          continue\n        fi\n        if _rnlctl_completion_is_global_option \"$token\"; then\n          if _rnlctl_completion_global_option_takes_value \"$token\"; then\n            expect_value=1\n          fi\n          continue\n        fi\n        case $token in\n")
	for _, option := range command.Options {
		patterns := completionOptionShellPatterns([]commandOptionSpec{option}, false)
		fmt.Fprintf(output, "          %s)\n            used_options+=(%s)\n", strings.Join(patterns, "|"), shellQuote("--"+option.Long))
		if option.Value != commandValueNone {
			output.WriteString("            expect_value=1\n")
		}
		output.WriteString("            continue\n            ;;\n")
		if option.Value == commandValueNone {
			continue
		}
		inlinePatterns := completionOptionShellPatterns([]commandOptionSpec{option}, true)
		fmt.Fprintf(output, "          %s)\n            used_options+=(%s)\n            continue\n            ;;\n", strings.Join(inlinePatterns, "|"), shellQuote("--"+option.Long))
	}
	output.WriteString("          -*)\n            continue\n            ;;\n          *)\n            used_arguments+=(\"$token\")\n            ;;\n        esac\n      done\n")
}

func writeZshOptionCandidates(output *strings.Builder, indent string, options []commandOptionSpec) {
	available := make([]commandOptionSpec, 0, len(options))
	conditional := make([]commandOptionSpec, 0, len(options))
	for _, option := range options {
		if len(option.UnavailableWith) == 0 {
			available = append(available, option)
		} else {
			conditional = append(conditional, option)
		}
	}
	output.WriteString(indent + "local -a candidates\n")
	output.WriteString(indent + "candidates=(\n")
	for _, candidate := range optionCandidates(available) {
		fmt.Fprintf(output, "%s  %s\n", indent, shellQuote(candidate.Value+":"+candidate.Description))
	}
	output.WriteString(indent + ")\n")
	for _, option := range conditional {
		fmt.Fprintf(output, "%sif %s; then\n", indent, zshOptionAvailableCondition(option))
		for _, candidate := range completionOptionCandidates(option) {
			fmt.Fprintf(output, "%s  candidates+=(%s)\n", indent, shellQuote(candidate.Value+":"+candidate.Description))
		}
		output.WriteString(indent + "fi\n")
	}
	fmt.Fprintf(output, "%s_describe -t options %s candidates\n", indent, shellQuote("option"))
}

func writeZshArgumentCandidates(output *strings.Builder, indent string, command commandSpec) {
	if !command.RepeatArgs {
		fmt.Fprintf(output, "%sif (( ${#used_arguments} == 0 )); then\n", indent)
		if !hasArgumentAvailabilityConditions(command) {
			writeZshCandidateValues(output, indent+"  ", command.Arguments)
			output.WriteString(indent + "fi\n")
			return
		}
		output.WriteString(indent + "  local -a candidates\n")
		output.WriteString(indent + "  candidates=()\n")
		for _, candidate := range command.Arguments {
			condition := zshArgumentAvailableCondition(command, candidate)
			if condition == "" {
				fmt.Fprintf(output, "%s  candidates+=(%s)\n", indent, shellQuote(candidate.Value+":"+candidate.Description))
				continue
			}
			fmt.Fprintf(output, "%s  if %s; then\n", indent, condition)
			fmt.Fprintf(output, "%s    candidates+=(%s)\n", indent, shellQuote(candidate.Value+":"+candidate.Description))
			output.WriteString(indent + "  fi\n")
		}
		output.WriteString(indent + "  (( ${#candidates} > 0 )) && _describe -t values 'value' candidates\n")
		output.WriteString(indent + "fi\n")
		return
	}
	if hasNoSpaceCandidate(command.Arguments) {
		for _, candidate := range command.Arguments {
			conditions := []string{"! _rnlctl_completion_argument_used " + shellQuote(candidate.Value) + " \"${used_arguments[@]}\""}
			if condition := zshArgumentAvailableCondition(command, candidate); condition != "" {
				conditions = append(conditions, condition)
			}
			fmt.Fprintf(output, "%sif %s; then\n", indent, strings.Join(conditions, " && "))
			fmt.Fprintf(output, "%s  compadd -S '' -- %s\n", indent, shellQuote(candidate.Value))
			output.WriteString(indent + "fi\n")
		}
		return
	}
	output.WriteString(indent + "local -a candidates\n")
	output.WriteString(indent + "candidates=()\n")
	for _, candidate := range command.Arguments {
		conditions := []string{"! _rnlctl_completion_argument_used " + shellQuote(candidate.Value) + " \"${used_arguments[@]}\""}
		if condition := zshArgumentAvailableCondition(command, candidate); condition != "" {
			conditions = append(conditions, condition)
		}
		fmt.Fprintf(output, "%sif %s; then\n", indent, strings.Join(conditions, " && "))
		fmt.Fprintf(output, "%s  candidates+=(%s)\n", indent, shellQuote(candidate.Value+":"+candidate.Description))
		output.WriteString(indent + "fi\n")
	}
	output.WriteString(indent + "(( ${#candidates} > 0 )) && _describe -t values 'value' candidates\n")
}

func hasArgumentAvailabilityConditions(command commandSpec) bool {
	for _, candidate := range command.Arguments {
		if len(optionsUnavailableWithArgument(command.Options, candidate)) != 0 {
			return true
		}
	}
	return false
}

func zshArgumentAvailableCondition(command commandSpec, candidate commandArgumentSpec) string {
	options := optionsUnavailableWithArgument(command.Options, candidate)
	conditions := make([]string, 0, len(options))
	for _, option := range options {
		conditions = append(conditions, "! _rnlctl_completion_argument_used "+shellQuote("--"+option.Long)+" \"${used_options[@]}\"")
	}
	return strings.Join(conditions, " && ")
}

func writeZshCandidateValues(output *strings.Builder, indent string, candidates []commandArgumentSpec) {
	if hasNoSpaceCandidate(candidates) {
		output.WriteString(indent + "compadd -S '' --")
		for _, candidate := range candidates {
			output.WriteByte(' ')
			output.WriteString(shellQuote(candidate.Value))
		}
		output.WriteByte('\n')
		return
	}
	writeZshDescribe(output, indent, "values", "value", candidates)
}

func zshOptionAvailableCondition(option commandOptionSpec) string {
	conditions := make([]string, 0, len(option.UnavailableWith))
	for _, argument := range option.UnavailableWith {
		conditions = append(conditions, "! _rnlctl_completion_argument_used "+shellQuote(argument)+" \"${used_arguments[@]}\"")
	}
	return strings.Join(conditions, " && ")
}

func writeZshDescribe(output *strings.Builder, indent, tag, label string, candidates []commandArgumentSpec) {
	output.WriteString(indent + "local -a candidates\n")
	output.WriteString(indent + "candidates=(\n")
	for _, candidate := range candidates {
		fmt.Fprintf(output, "%s  %s\n", indent, shellQuote(candidate.Value+":"+candidate.Description))
	}
	output.WriteString(indent + ")\n")
	fmt.Fprintf(output, "%s_describe -t %s %s candidates\n", indent, tag, shellQuote(label))
}
