#!/usr/bin/env bash
# Install a pinned rw-core release and verified optional ASN database.
# shellcheck source-path=SCRIPTDIR
set -euo pipefail

PINNED_XRAY_VERSION="v26.6.27"
PINNED_XRAY_COMMIT="45cf2898ab12e97a55dd8f1f3d78d903340bdc9e"
PINNED_AMD64_SHA256="b3e5902d06d6282fe53cfa2fc426058b9aeaa429b2c812e20887cd47f26d08bf"
PINNED_ARM64_SHA256="13a251379bea366c2cf10363ad71e75734193d401f26f518bf0c25e5c8f8c931"

XRAY_CORE_VERSION="${XRAY_CORE_VERSION:-$PINNED_XRAY_VERSION}"
XRAY_CORE_SHA256="${XRAY_CORE_SHA256:-}"
CUSTOM_CORE_URL="${CUSTOM_CORE_URL:-}"
CUSTOM_CORE_SHA256="${CUSTOM_CORE_SHA256:-}"
NODE_ENV="${NODE_ENV:-/etc/remnanode/node.env}"
XRAY_BIN="${XRAY_BIN:-/usr/local/lib/remnanode/rw-core}"
GEO_DIR="${GEO_DIR:-/usr/local/share/remnanode/xray}"
ASN_DB_URL="${ASN_DB_URL:-}"
ASN_DB_SHA256="${ASN_DB_SHA256:-}"
ASN_DB_PATH="${ASN_DB_PATH:-/usr/local/share/remnanode/asn/asn-prefixes.bin}"
RNL_REPO="${RNL_REPO:-Luxiaba/remnanode-lite}"
RNL_TAG="${RNL_TAG:-v2.8.0-rnl.1}"
RNL_INSTALL_ASN="${RNL_INSTALL_ASN:-1}"
DRY_RUN=0
TMP_DIR=""
ASN_SOURCE=""
ASN_TRANSACTIONAL=0
INSTALL_ARMED=0
EXTERNAL_ASSET_ROLLBACK="${RNL_EXTERNAL_ASSET_ROLLBACK:-0}"

readonly XRAY_ARCHIVE_MAX_BYTES=134217728
readonly XRAY_CORE_MAX_BYTES=134217728
readonly XRAY_GEO_FILE_MAX_BYTES=67108864
readonly XRAY_ASN_MAX_BYTES=67108864
readonly XRAY_INITIAL_WORK_BYTES=402653184
readonly XRAY_SPACE_SAFETY_BYTES=67108864
readonly XRAY_ARCHIVE_MAX_ENTRIES=64
readonly XRAY_DOWNLOAD_CONNECT_TIMEOUT_SECONDS=15
readonly XRAY_DOWNLOAD_MAX_TIME_SECONDS=300
readonly XRAY_DOWNLOAD_SPEED_LIMIT_BYTES=1024
readonly XRAY_DOWNLOAD_SPEED_TIME_SECONDS=60
readonly XRAY_ARCHIVE_TIMEOUT_SECONDS=120

XRAY_SPACE_DEVICE_IDS=()
XRAY_SPACE_PATHS=()
XRAY_SPACE_REQUIRED=()

usage() {
  cat <<'EOF'
Usage: install-xray.sh [options]

Options:
  --version VERSION      rw-core release (default: v26.6.27)
  --sha256 HEX           required when VERSION is not the pinned release
  --dry-run              print actions without changing the system
  --help                 show this help

Environment:
  CUSTOM_CORE_URL        raw custom Linux core binary
  CUSTOM_CORE_SHA256     mandatory SHA-256 for CUSTOM_CORE_URL
  ASN_DB_URL             compact RWASNDB file generated by cmd/asn-builder
  ASN_DB_SHA256          mandatory SHA-256 for ASN_DB_URL
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --version) XRAY_CORE_VERSION="${2:-}"; shift 2 ;;
    --sha256) XRAY_CORE_SHA256="${2:-}"; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    --help|-h) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

bootstrap_helper_is_trusted() {
  local script="$1" helper="$2" script_owner helper_owner trusted_uid
  local logical_dir physical_dir current owner mode links size function_name
  [ -f "$script" ] && [ ! -L "$script" ] \
    && [ -f "$helper" ] && [ ! -L "$helper" ] || return 1
  script_owner="$(stat -c '%u:%g' "$script" 2>/dev/null \
    || stat -f '%u:%g' "$script" 2>/dev/null)" || return
  helper_owner="$(stat -c '%u:%g' "$helper" 2>/dev/null \
    || stat -f '%u:%g' "$helper" 2>/dev/null)" || return
  trusted_uid="${script_owner%%:*}"
  [ "${helper_owner%%:*}" = "$trusted_uid" ] || return 1
  for current in "$script" "$helper"; do
    mode="$(stat -c '%a' "$current" 2>/dev/null \
      || stat -f '%Lp' "$current" 2>/dev/null)" || return
    links="$(stat -c '%h' "$current" 2>/dev/null \
      || stat -f '%l' "$current" 2>/dev/null)" || return
    [[ "$mode" =~ ^[0-7]{3,4}$ ]] && [ $((8#$mode & 022)) -eq 0 ] \
      && [ "$links" = 1 ] || return 1
  done
  logical_dir="$(cd "$(dirname "$helper")" && pwd -L)" || return
  physical_dir="$(cd "$(dirname "$helper")" && pwd -P)" || return
  [ "$logical_dir" = "$physical_dir" ] || return 1
  current="$physical_dir"
  while :; do
    [ -d "$current" ] && [ ! -L "$current" ] || return 1
    owner="$(stat -c '%u:%g' "$current" 2>/dev/null \
      || stat -f '%u:%g' "$current" 2>/dev/null)" || return
    mode="$(stat -c '%a' "$current" 2>/dev/null \
      || stat -f '%Lp' "$current" 2>/dev/null)" || return
    { [ "${owner%%:*}" = 0 ] || [ "${owner%%:*}" = "$trusted_uid" ]; } \
      && [[ "$mode" =~ ^[0-7]{3,4}$ ]] \
      && [ $((8#$mode & 022)) -eq 0 ] || return 1
    [ "$current" = / ] && break
    current="$(dirname "$current")" || return
  done
  size="$(wc -c <"$helper" | tr -d '[:space:]')" || return
  [[ "$size" =~ ^[0-9]+$ ]] && [ "$size" -le 1048576 ] || return 1
  for function_name in \
    installer_acquire_lock installer_run_nested installer_run_without_lock; do
    grep -Eq "^${function_name}\\(\\) [({]$" "$helper" || return 1
  done
}

bootstrap_installed_lock_helper() {
  local link=/usr/local/lib/remnanode/support-current target helper owner
  [ -L "$link" ] || return 1
  owner="$(stat -c '%u:%g' "$link" 2>/dev/null \
    || stat -f '%u:%g' "$link" 2>/dev/null)" || return
  [ "$owner" = 0:0 ] || return 1
  target="$(readlink "$link")" || return
  [ "$target" = "support/${RNL_TAG}" ] || return 1
  helper="/usr/local/lib/remnanode/${target}/scripts/install-env-helpers.sh"
  bootstrap_helper_is_trusted "$helper" "$helper" || return
  printf '%s' "$helper"
}

bootstrap_run_without_installer_lock() (
  local fd="${RNL_INSTALLER_LOCK_FD:-${INSTALLER_LOCK_FD:-}}"
  if [[ "$fd" =~ ^[0-9]+$ ]] && [ "${#fd}" -le 6 ] && [ "$fd" -ge 10 ]; then
    exec {fd}>&-
  fi
  unset RNL_INSTALLER_LOCK_FD RNL_INSTALLER_LOCK_ID
  "$@"
)

load_installer_helpers() {
  local helpers_dir helpers_tmp helpers_bytes installed_helper function_name
  local -a helpers_status
  if [ -n "${BASH_SOURCE[0]:-}" ]; then
    helpers_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    if bootstrap_helper_is_trusted \
      "${BASH_SOURCE[0]}" "${helpers_dir}/install-env-helpers.sh"; then
      # shellcheck source=install-env-helpers.sh
      source "${helpers_dir}/install-env-helpers.sh"
      return
    fi
  fi
  if installed_helper="$(bootstrap_installed_lock_helper)"; then
    # shellcheck disable=SC1090
    source "$installed_helper"
    return
  fi
  if ! [[ "$RNL_REPO" =~ ^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9][A-Za-z0-9_.-]*$ ]] \
    || ! [[ "$RNL_TAG" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]]; then
    echo "invalid RNL_REPO or RNL_TAG for installer helper bootstrap" >&2
    return 2
  fi
  if ! command -v curl >/dev/null 2>&1 || ! command -v head >/dev/null 2>&1; then
    echo "curl and head are required to bootstrap installer locking" >&2
    return 1
  fi
  helpers_tmp="$(mktemp -d /var/tmp/remnanode-bootstrap.XXXXXX)" || return
  set +o pipefail
  bootstrap_run_without_installer_lock \
    curl --fail --location --silent --show-error --proto '=https' --tlsv1.2 \
    --connect-timeout 15 --max-time 60 --speed-limit 1024 --speed-time 30 \
    --max-filesize 1048576 \
    "https://raw.githubusercontent.com/${RNL_REPO}/${RNL_TAG}/scripts/install-env-helpers.sh" \
    | bootstrap_run_without_installer_lock head -c 1048577 \
      >"${helpers_tmp}/install-env-helpers.sh"
  helpers_status=("${PIPESTATUS[@]}")
  set -o pipefail
  helpers_bytes="$(wc -c <"${helpers_tmp}/install-env-helpers.sh" | tr -d '[:space:]')"
  if [ "${helpers_status[0]:-1}" -ne 0 ] \
    || [ "${helpers_status[1]:-1}" -ne 0 ] \
    || [ "$helpers_bytes" -gt 1048576 ]; then
    rm -rf "$helpers_tmp"
    echo "installer helper bootstrap failed or exceeded 1048576 bytes" >&2
    return 1
  fi
  for function_name in \
    installer_acquire_lock installer_run_nested installer_run_without_lock; do
    grep -Eq "^${function_name}\\(\\) [({]$" \
      "${helpers_tmp}/install-env-helpers.sh" || {
      rm -rf "$helpers_tmp"
      echo "installer helper is missing lock API: ${function_name}" >&2
      return 1
    }
  done
  # shellcheck disable=SC1091
  if ! source "${helpers_tmp}/install-env-helpers.sh"; then
    rm -rf "$helpers_tmp"
    return 1
  fi
  rm -rf "$helpers_tmp"
}

if [ "${RNL_INSTALL_XRAY_LIBRARY_ONLY:-0}" != 1 ] && [ "$DRY_RUN" -eq 0 ]; then
  if [ "$(id -u)" -ne 0 ]; then
    echo "run as root: sudo bash install-xray.sh" >&2
    exit 1
  fi
  load_installer_helpers
fi

require_root() {
  if [ "$DRY_RUN" -eq 0 ] && [ "$(id -u)" -ne 0 ]; then
    echo "run as root: sudo bash install-xray.sh" >&2
    exit 1
  fi
}

load_env_var() {
  local key="$1" file="$2" line value
  [ -z "${!key:-}" ] || return 0
  [ -f "$file" ] || return 0
  line="$(grep -E "^[[:space:]]*(export[[:space:]]+)?${key}[[:space:]]*=" "$file" 2>/dev/null | tail -n 1 || true)"
  [ -n "$line" ] || return 0
  value="${line#*=}"
  value="$(printf '%s' "$value" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
  case "$value" in
    \"*\") value=${value#\"}; value=${value%\"} ;;
    \'*\') value=${value#\'}; value=${value%\'} ;;
  esac
  [ -n "$value" ] || return 0
  printf -v "$key" '%s' "$value"
}

download_file() {
  local url="$1" output="$2" max_bytes="${3:?download size limit is required}"
  local attempt size curl_status head_status
  local -a pipeline_status
  case "$url" in https://*) ;; *) echo "download URL must use HTTPS: $url" >&2; return 1 ;; esac
  if ! [[ "$max_bytes" =~ ^[1-9][0-9]*$ ]] \
    || [ "${#max_bytes}" -gt 10 ] || [ "$max_bytes" -gt 1073741824 ]; then
    echo "invalid download size limit: $max_bytes" >&2
    return 2
  fi
  command -v curl >/dev/null 2>&1 || {
    echo "curl is required for size-bounded HTTPS downloads" >&2
    return 1
  }

  for attempt in 1 2 3; do
    rm -f "$output"
    set +o pipefail
    installer_run_without_lock curl --fail --location --silent --show-error \
      --proto '=https' --tlsv1.2 \
      --connect-timeout "$XRAY_DOWNLOAD_CONNECT_TIMEOUT_SECONDS" \
      --max-time "$XRAY_DOWNLOAD_MAX_TIME_SECONDS" \
      --speed-limit "$XRAY_DOWNLOAD_SPEED_LIMIT_BYTES" \
      --speed-time "$XRAY_DOWNLOAD_SPEED_TIME_SECONDS" \
      "$url" \
      | installer_run_without_lock head -c $((max_bytes + 1)) >"$output"
    pipeline_status=("${PIPESTATUS[@]}")
    set -o pipefail
    curl_status="${pipeline_status[0]:-1}"
    head_status="${pipeline_status[1]:-1}"
    size="$(file_size_bytes "$output")"

    if ! [[ "$size" =~ ^[0-9]+$ ]] || [ "$size" -gt "$max_bytes" ]; then
      rm -f "$output"
      echo "download exceeds hard limit: ${size:-unknown} > $max_bytes bytes" >&2
      return 1
    fi
    if [ "$curl_status" -eq 0 ] && [ "$head_status" -eq 0 ]; then
      return 0
    fi
    rm -f "$output"
    [ "$attempt" -eq 3 ] || sleep "$attempt"
  done
  return 1
}

file_size_bytes() {
  wc -c <"$1" | tr -d '[:space:]'
}

require_file_size_at_most() {
  local file="$1" max_bytes="$2" label="$3" size
  [ -f "$file" ] || { echo "$label is missing: $file" >&2; return 1; }
  size="$(file_size_bytes "$file")"
  if ! [[ "$size" =~ ^[0-9]+$ ]] || [ "$size" -gt "$max_bytes" ]; then
    echo "$label exceeds hard limit: ${size:-unknown} > $max_bytes bytes" >&2
    return 1
  fi
}

installer_temp_root() {
  printf '%s' "${RNL_TMP_ROOT:-/var/lib/remnanode-installer}"
}

validate_installer_temp_root_path() {
  local root="$1" component current="/"
  local -a components
  case "$root" in
    /) echo "refusing / as RNL_TMP_ROOT" >&2; return 1 ;;
    /*) ;;
    *) echo "RNL_TMP_ROOT must be absolute: $root" >&2; return 2 ;;
  esac
  if [[ "$root" == */ ]] || [[ "$root" == *//* ]] \
    || [[ "$root" == *$'\n'* ]] || [[ "$root" == *$'\r'* ]]; then
    echo "RNL_TMP_ROOT is not a normalized path: $root" >&2
    return 2
  fi

  if ! installer_ancestor_is_safe /; then
    echo "RNL_TMP_ROOT ancestor is not root-owned and non-writable: /" >&2
    return 1
  fi
  IFS=/ read -r -a components <<<"${root#/}"
  for component in "${components[@]}"; do
    case "$component" in
      ''|.|..) echo "RNL_TMP_ROOT has an unsafe path component: $root" >&2; return 2 ;;
    esac
    current="${current%/}/${component}"
    if [ -L "$current" ]; then
      echo "RNL_TMP_ROOT has a symlink component: $current" >&2
      return 1
    fi
    if [ -e "$current" ] && [ ! -d "$current" ]; then
      echo "RNL_TMP_ROOT ancestor is not a directory: $current" >&2
      return 1
    fi
    if [ -e "$current" ] && ! installer_ancestor_is_safe "$current"; then
      echo "RNL_TMP_ROOT ancestor is not root-owned and non-writable: $current" >&2
      return 1
    fi
  done
}

installer_path_owner_ids() {
  local path="$1" owner
  if owner="$(stat -c '%u:%g' "$path" 2>/dev/null)"; then
    printf '%s' "$owner"
    return 0
  fi
  stat -f '%u:%g' "$path" 2>/dev/null
}

installer_path_has_root_owner() {
  [ "$(installer_path_owner_ids "$1")" = "0:0" ]
}

installer_path_mode() {
  local path="$1" mode
  if mode="$(stat -c '%a' "$path" 2>/dev/null)"; then
    printf '%s' "$mode"
    return 0
  fi
  stat -f '%Lp' "$path" 2>/dev/null
}

installer_path_link_count() {
  local path="$1" count
  if count="$(stat -c '%h' "$path" 2>/dev/null)"; then
    printf '%s' "$count"
    return 0
  fi
  stat -f '%l' "$path" 2>/dev/null
}

installer_ancestor_is_safe() {
  local path="$1" mode
  installer_path_has_root_owner "$path" || return 1
  mode="$(installer_path_mode "$path")" || return 1
  [[ "$mode" =~ ^[0-7]{3,4}$ ]] || return 1
  [ $((8#$mode & 022)) -eq 0 ]
}

installer_temp_root_is_empty() {
  local root="$1" entry
  entry="$(find "$root" -mindepth 1 -maxdepth 1 -print -quit)" || return 1
  [ -z "$entry" ]
}

validate_installer_temp_root_marker() {
  local root="$1" marker="${1}/.remnanode-installer-root"
  local expected="remnanode-installer-root-v1" size mode links
  installer_ancestor_is_safe "$root" || {
    echo "RNL_TMP_ROOT must be root-owned and non-writable before marker use: $root" >&2
    return 1
  }
  [ -f "$marker" ] && [ ! -L "$marker" ] || {
    echo "non-empty RNL_TMP_ROOT lacks a regular marker: $marker" >&2
    return 1
  }
  if ! installer_path_has_root_owner "$marker"; then
    echo "RNL_TMP_ROOT marker must be owned by root:root: $marker" >&2
    return 1
  fi
  links="$(installer_path_link_count "$marker")" || return 1
  [ "$links" = 1 ] || { echo "RNL_TMP_ROOT marker has hard links: $marker" >&2; return 1; }
  mode="$(installer_path_mode "$marker")" || return 1
  [[ "$mode" =~ ^[0-7]{3,4}$ ]] && [ $((8#$mode & 022)) -eq 0 ] || {
    echo "RNL_TMP_ROOT marker is group/other-writable: $marker" >&2
    return 1
  }
  size="$(file_size_bytes "$marker")"
  if [ "$size" -ne $((${#expected} + 1)) ] || [ "$(cat "$marker")" != "$expected" ]; then
    echo "invalid RNL_TMP_ROOT marker contents: $marker" >&2
    return 1
  fi
}

ensure_installer_temp_root() {
  local root marker expected="remnanode-installer-root-v1"
  root="$(installer_temp_root)"
  validate_installer_temp_root_path "$root" || return
  if [ ! -e "$root" ]; then
    (umask 077; mkdir -p "$root") || return
  fi
  validate_installer_temp_root_path "$root" || return
  [ -d "$root" ] || { echo "RNL_TMP_ROOT is not a directory: $root" >&2; return 1; }
  if ! installer_path_has_root_owner "$root"; then
    echo "RNL_TMP_ROOT must be owned by root:root before use: $root" >&2
    return 1
  fi

  marker="${root}/.remnanode-installer-root"
  if installer_temp_root_is_empty "$root"; then
    if ! (umask 077; set -o noclobber; printf '%s\n' "$expected" >"$marker") 2>/dev/null; then
      echo "failed to atomically create RNL_TMP_ROOT marker: $marker" >&2
      return 1
    fi
  fi
  validate_installer_temp_root_marker "$root" || return

  chmod 0700 "$root" || return
  chmod 0600 "$marker" || return
  validate_installer_temp_root_path "$root" || return
  validate_installer_temp_root_marker "$root"
}

make_temp_dir() {
  local root
  ensure_installer_temp_root || return
  root="$(installer_temp_root)"
  mktemp -d "${root}/xray.XXXXXX"
}

path_disk_bytes() {
  local path="$1" kilobytes
  if [ -e "$path" ] || [ -L "$path" ]; then
    if ! kilobytes="$(du -sk "$path" 2>/dev/null | awk 'NR == 1 { print $1; exit }')" \
      || ! [[ "$kilobytes" =~ ^[0-9]+$ ]]; then
      echo "cannot determine disk usage for $path" >&2
      return 1
    fi
    printf '%s' "$((kilobytes * 1024))"
  else
    printf '0'
  fi
}

require_free_space() {
  local path="$1" required="$2" available_kb available
  available_kb="$(df -Pk "$path" | awk 'NR == 2 { print $4; exit }')"
  [[ "$available_kb" =~ ^[0-9]+$ ]] || { echo "cannot determine free disk space for $path" >&2; return 1; }
  available=$((available_kb * 1024))
  if [ "$available" -lt "$required" ]; then
    echo "insufficient disk space: available=$available required=$required path=$path" >&2
    return 1
  fi
}

existing_parent() {
  local path="$1" parent="$1"
  while [ ! -e "$parent" ]; do
    [ "$parent" != / ] || break
    parent="$(dirname "$parent")"
  done
  printf '%s' "$parent"
}

filesystem_device_id() {
  local path="$1" device
  if device="$(stat -c '%d' "$path" 2>/dev/null)"; then
    printf '%s' "$device"
    return 0
  fi
  if device="$(stat -f '%d' "$path" 2>/dev/null)"; then
    printf '%s' "$device"
    return 0
  fi
  echo "cannot determine filesystem device for $path" >&2
  return 1
}

reset_space_budget() {
  XRAY_SPACE_DEVICE_IDS=()
  XRAY_SPACE_PATHS=()
  XRAY_SPACE_REQUIRED=()
}

add_space_budget() {
  local target="$1" additional="$2" path device current total i
  if ! [[ "$additional" =~ ^[0-9]+$ ]]; then
    echo "invalid disk space budget for $target: $additional" >&2
    return 1
  fi
  path="$(existing_parent "$target")" || return
  device="$(filesystem_device_id "$path")" || return
  for ((i = 0; i < ${#XRAY_SPACE_DEVICE_IDS[@]}; i++)); do
    if [ "${XRAY_SPACE_DEVICE_IDS[$i]}" = "$device" ]; then
      current="${XRAY_SPACE_REQUIRED[$i]}"
      total=$((current + additional))
      if [ "$total" -lt "$current" ]; then
        echo "disk space budget overflow for $target" >&2
        return 1
      fi
      XRAY_SPACE_REQUIRED[i]="$total"
      return 0
    fi
  done
  XRAY_SPACE_DEVICE_IDS+=("$device")
  XRAY_SPACE_PATHS+=("$path")
  XRAY_SPACE_REQUIRED+=("$additional")
}

require_space_budget() {
  local required total i
  for ((i = 0; i < ${#XRAY_SPACE_DEVICE_IDS[@]}; i++)); do
    required="${XRAY_SPACE_REQUIRED[$i]}"
    total=$((required + XRAY_SPACE_SAFETY_BYTES))
    if [ "$total" -lt "$required" ]; then
      echo "disk space budget overflow for ${XRAY_SPACE_PATHS[$i]}" >&2
      return 1
    fi
    if ! require_free_space "${XRAY_SPACE_PATHS[$i]}" "$total"; then
      return 1
    fi
  done
}

asset_backup_bytes() {
  local include_asn="$1" bytes size target
  bytes=0
  for target in "$XRAY_BIN" "$GEO_DIR/geoip.dat" "$GEO_DIR/geosite.dat"; do
    size="$(path_disk_bytes "$target")" || return
    bytes=$((bytes + size))
  done
  if [ "$include_asn" -eq 1 ]; then
    size="$(path_disk_bytes "$ASN_DB_PATH")" || return
    bytes=$((bytes + size))
  fi
  printf '%s' "$bytes"
}

xray_validate_absolute_path() {
  local path="$1"
  case "$path" in
    /|'') echo "refusing an empty path or / as an install target" >&2; return 1 ;;
    /*) ;;
    *) echo "install target must be absolute: $path" >&2; return 2 ;;
  esac
  if [[ "$path" == */ ]] || [[ "$path" == *//* ]] \
    || [[ "$path" == *$'\n'* ]] || [[ "$path" == *$'\r'* ]] \
    || [[ "/${path#/}/" == */./* ]] || [[ "/${path#/}/" == */../* ]]; then
    echo "install target is not a normalized path: $path" >&2
    return 2
  fi
}

xray_root_directory_is_safe() {
  local path="$1" mode
  [ -d "$path" ] && [ ! -L "$path" ] || return 1
  installer_path_has_root_owner "$path" || return 1
  mode="$(installer_path_mode "$path")" || return 1
  [[ "$mode" =~ ^[0-7]{3,4}$ ]] || return 1
  [ $((8#$mode & 022)) -eq 0 ]
}

xray_validate_parent_path() {
  local path="$1" parent component current="/"
  local -a components
  xray_validate_absolute_path "$path" || return
  parent="$(dirname "$path")"
  xray_root_directory_is_safe / || {
    echo "install target ancestor is not root-owned and non-writable: /" >&2
    return 1
  }
  [ "$parent" = / ] && return 0

  IFS=/ read -r -a components <<<"${parent#/}"
  for component in "${components[@]}"; do
    current="${current%/}/${component}"
    if [ -L "$current" ]; then
      echo "install target has a symlink ancestor: $current" >&2
      return 1
    fi
    if [ -e "$current" ] && ! xray_root_directory_is_safe "$current"; then
      echo "install target ancestor is not root-owned and non-writable: $current" >&2
      return 1
    fi
  done
}

xray_validate_existing_directory() {
  local path="$1"
  xray_validate_parent_path "$path" || return
  if [ ! -e "$path" ] && [ ! -L "$path" ]; then
    return 0
  fi
  xray_root_directory_is_safe "$path" || {
    echo "install target directory is unsafe or a symlink: $path" >&2
    return 1
  }
}

xray_ensure_root_directory() {
  local path="$1" mode="${2:-0755}"
  xray_validate_existing_directory "$path" || return
  if [ ! -d "$path" ]; then
    install -d -o root -g root -m "$mode" "$path" || return
  fi
  xray_validate_existing_directory "$path"
}

xray_validate_existing_file() {
  local path="$1" mode links
  xray_validate_parent_path "$path" || return
  if [ ! -e "$path" ] && [ ! -L "$path" ]; then
    return 0
  fi
  [ -f "$path" ] && [ ! -L "$path" ] || {
    echo "install target is not a regular file or is a symlink: $path" >&2
    return 1
  }
  installer_path_has_root_owner "$path" || {
    echo "install target must be owned by root:root: $path" >&2
    return 1
  }
  links="$(installer_path_link_count "$path")" || return 1
  [ "$links" = 1 ] || { echo "install target has hard links: $path" >&2; return 1; }
  mode="$(installer_path_mode "$path")" || return 1
  [[ "$mode" =~ ^[0-7]{3,4}$ ]] && [ $((8#$mode & 022)) -eq 0 ] || {
    echo "install target is group/other-writable: $path" >&2
    return 1
  }
}

validate_xray_install_layout() {
  xray_validate_existing_directory "$(dirname "$XRAY_BIN")" || return
  xray_validate_existing_directory "$GEO_DIR" || return
  xray_validate_existing_directory "$(dirname "$ASN_DB_PATH")" || return
  xray_validate_existing_file "$XRAY_BIN" || return
  xray_validate_existing_file "$GEO_DIR/geoip.dat" || return
  xray_validate_existing_file "$GEO_DIR/geosite.dat" || return
  xray_validate_existing_file "$ASN_DB_PATH"
}

run_with_timeout() {
  local seconds="$1"
  shift
  command -v timeout >/dev/null 2>&1 || {
    echo "timeout is required for bounded archive processing" >&2
    return 1
  }
  installer_run_without_lock timeout "$seconds" "$@"
}

running_pids_for_install_target() {
  local binary="$1" proc_root="${RNL_PROC_ROOT:-/proc}" exe pid target
  for exe in "$proc_root"/[0-9]*/exe; do
    [ -e "$exe" ] || [ -L "$exe" ] || continue
    pid="${exe%/exe}"
    pid="${pid##*/}"
    if [ -e "$binary" ] && [ "$exe" -ef "$binary" ]; then
      printf '%s\n' "$pid"
      continue
    fi
    target="$(readlink "$exe" 2>/dev/null || true)"
    if [ "$target" = "$binary" ] || [ "$target" = "$binary (deleted)" ]; then
      printf '%s\n' "$pid"
    fi
  done
}

require_install_target_stopped() {
  local binary="$1" pids
  pids="$(running_pids_for_install_target "$binary")"
  if [ -n "$pids" ]; then
    echo "refusing to replace running binary $binary: ${pids//$'\n'/,}" >&2
    return 1
  fi
}

preflight_disk_space() {
  local root temp_required backup_bytes=0 include_asn=0
  validate_xray_install_layout || return
  root="$(installer_temp_root)"
  ensure_installer_temp_root || return
  if [ "$RNL_INSTALL_ASN" != 0 ]; then
    include_asn=1
  fi
  if [ "$EXTERNAL_ASSET_ROLLBACK" != 1 ]; then
    backup_bytes="$(asset_backup_bytes "$include_asn")" || return
  fi
  temp_required=$((backup_bytes + XRAY_INITIAL_WORK_BYTES))
  if [ -n "$CUSTOM_CORE_URL" ]; then
    temp_required=$((temp_required + XRAY_CORE_MAX_BYTES))
  fi
  if [ "$include_asn" -eq 1 ]; then
    temp_required=$((temp_required + XRAY_ASN_MAX_BYTES + 1048576))
  fi

  reset_space_budget
  add_space_budget "$root" "$temp_required" || return
  add_space_budget "$(dirname "$XRAY_BIN")" "$XRAY_CORE_MAX_BYTES" || return
  add_space_budget "$GEO_DIR" "$XRAY_GEO_FILE_MAX_BYTES" || return
  add_space_budget "$GEO_DIR" "$XRAY_GEO_FILE_MAX_BYTES" || return
  if [ "$include_asn" -eq 1 ]; then
    add_space_budget "$(dirname "$ASN_DB_PATH")" "$XRAY_ASN_MAX_BYTES" || return
  fi
  require_space_budget
}

validate_zip_structure() {
  local archive="$1" count item matches
  count="$(run_with_timeout "$XRAY_ARCHIVE_TIMEOUT_SECONDS" unzip -Z -1 "$archive" \
    | awk 'END { print NR + 0 }')"
  [ "$count" -le "$XRAY_ARCHIVE_MAX_ENTRIES" ] || {
    echo "rw-core archive has too many entries: $count" >&2
    return 1
  }
  for item in xray geoip.dat geosite.dat; do
    matches="$(run_with_timeout "$XRAY_ARCHIVE_TIMEOUT_SECONDS" unzip -Z -1 "$archive" \
      | awk -v wanted="$item" '$0 == wanted { count++ } END { print count + 0 }')"
    [ "$matches" -eq 1 ] || {
      echo "rw-core archive must contain exactly one root entry named $item" >&2
      return 1
    }
  done
}

zip_entry_size() {
  local archive="$1" item="$2"
  run_with_timeout "$XRAY_ARCHIVE_TIMEOUT_SECONDS" unzip -l "$archive" "$item" \
    | awk -v wanted="$item" '
    $4 == wanted && $1 ~ /^[0-9]+$/ { size = $1; count++ }
    END { if (count != 1) exit 1; print size }
  '
}

preflight_asset_space() {
  local archive="$1" root zip_core geoip geosite custom_size=0 asn_size=0
  local selected_core temp_growth backup_bytes=0
  validate_xray_install_layout || return
  root="$(installer_temp_root)"
  zip_core="$(zip_entry_size "$archive" xray)"
  geoip="$(zip_entry_size "$archive" geoip.dat)"
  geosite="$(zip_entry_size "$archive" geosite.dat)"
  [ "$zip_core" -le "$XRAY_CORE_MAX_BYTES" ] || {
    echo "xray exceeds extraction hard limit: $XRAY_CORE_MAX_BYTES bytes" >&2
    return 1
  }
  [ "$geoip" -le "$XRAY_GEO_FILE_MAX_BYTES" ] \
    && [ "$geosite" -le "$XRAY_GEO_FILE_MAX_BYTES" ] || {
      echo "geo asset exceeds extraction hard limit: $XRAY_GEO_FILE_MAX_BYTES bytes" >&2
      return 1
    }
  if [ -f "$TMP_DIR/custom-core" ]; then
    custom_size="$(file_size_bytes "$TMP_DIR/custom-core")"
    selected_core=$custom_size
  else
    selected_core=$zip_core
  fi
  if [ -n "$ASN_SOURCE" ]; then
    asn_size="$(file_size_bytes "$ASN_SOURCE")"
  fi
  if [ "$EXTERNAL_ASSET_ROLLBACK" != 1 ]; then
    if [ -n "$ASN_SOURCE" ]; then
      backup_bytes="$(asset_backup_bytes 1)" || return
    else
      backup_bytes="$(asset_backup_bytes 0)" || return
    fi
  fi

  # The archive, optional custom core, and ASN source already consume space at
  # this point. Only extraction, backups, and target staging remain as growth.
  temp_growth=$((zip_core + geoip + geosite + backup_bytes))
  reset_space_budget
  add_space_budget "$root" "$temp_growth" || return
  add_space_budget "$(dirname "$XRAY_BIN")" "$selected_core" || return
  add_space_budget "$GEO_DIR" "$geoip" || return
  add_space_budget "$GEO_DIR" "$geosite" || return
  if [ -n "$ASN_SOURCE" ]; then
    add_space_budget "$(dirname "$ASN_DB_PATH")" "$asn_size" || return
  fi
  require_space_budget
}

extract_zip_entry_limited() {
  local archive="$1" item="$2" output="$3" max_bytes="$4" unzip_status size
  set +o pipefail
  run_with_timeout "$XRAY_ARCHIVE_TIMEOUT_SECONDS" unzip -p "$archive" "$item" \
    | head -c $((max_bytes + 1)) >"$output"
  unzip_status=${PIPESTATUS[0]}
  set -o pipefail
  size="$(file_size_bytes "$output")"
  if [ "$size" -gt "$max_bytes" ]; then
    rm -f "$output"
    echo "$item exceeds extraction hard limit: $max_bytes bytes" >&2
    return 1
  fi
  if [ "$unzip_status" -ne 0 ]; then
    rm -f "$output"
    echo "failed to extract $item from verified archive" >&2
    return 1
  fi
  [ "$size" -gt 0 ] || { rm -f "$output"; echo "empty archive entry: $item" >&2; return 1; }
}

verify_sha256() {
  local file="$1" expected="$2" actual
  if ! [[ "$expected" =~ ^[0-9a-fA-F]{64}$ ]]; then
    echo "invalid SHA-256 for $file" >&2
    return 1
  fi
  if command -v sha256sum >/dev/null 2>&1; then
    actual="$(sha256sum "$file" | awk '{print $1}')"
  else
    actual="$(shasum -a 256 "$file" | awk '{print $1}')"
  fi
  if [ "${actual,,}" != "${expected,,}" ]; then
    echo "SHA-256 mismatch for $file: got $actual, want $expected" >&2
    return 1
  fi
}

atomic_install() {
  local source="$1" target="$2" mode="$3" staged parent
  parent="$(dirname "$target")"
  xray_ensure_root_directory "$parent" 0755 || return
  xray_validate_existing_file "$target" || return
  staged="${target}.new.$$"
  if ! rm -f "$staged"; then
    echo "failed to clear stale install staging file: $staged" >&2
    return 1
  fi
  if ! install -o root -g root -m "$mode" "$source" "$staged"; then
    if ! rm -f "$staged"; then
      echo "failed to remove incomplete install staging file: $staged" >&2
    fi
    return 1
  fi
  if ! mv -f "$staged" "$target"; then
    if ! rm -f "$staged"; then
      echo "failed to remove rejected install staging file: $staged" >&2
    fi
    return 1
  fi
  xray_validate_existing_file "$target"
}

backup_asset() {
  local target="$1" name="$2"
  xray_validate_existing_file "$target" || return
  if [ -e "$target" ] || [ -L "$target" ]; then
    if ! cp -a "$target" "$TMP_DIR/backup/$name"; then
      echo "failed to back up asset: $target" >&2
      return 1
    fi
  else
    if ! : >"$TMP_DIR/backup/$name.absent"; then
      echo "failed to record absent asset: $target" >&2
      return 1
    fi
  fi
}

restore_asset() {
  local name="$1" target="$2" parent backup absent staged
  parent="$(dirname "$target")"
  backup="$TMP_DIR/backup/$name"
  absent="$TMP_DIR/backup/$name.absent"
  staged="${target}.rollback.$$"
  xray_ensure_root_directory "$parent" 0755 || return
  xray_validate_existing_file "$target" || return

  if [ -e "$backup" ] || [ -L "$backup" ]; then
    xray_validate_existing_file "$backup" || {
      echo "unsafe rollback backup for $target: $backup" >&2
      return 1
    }
    if ! rm -f "$staged"; then
      echo "failed to clear rollback staging file: $staged" >&2
      return 1
    fi
    if ! cp -a "$backup" "$staged"; then
      echo "failed to stage rollback backup for $target" >&2
      return 1
    fi
    if ! xray_validate_existing_file "$staged"; then
      echo "staged rollback asset failed validation: $staged" >&2
      if ! rm -f "$staged"; then
        echo "failed to remove invalid rollback staging file: $staged" >&2
      fi
      return 1
    fi
    if ! mv -f "$staged" "$target"; then
      echo "failed to atomically restore asset: $target" >&2
      return 1
    fi
  elif [ -f "$absent" ] && [ ! -L "$absent" ]; then
    if ! rm -f "$staged" "$target"; then
      echo "failed to restore absent asset state: $target" >&2
      return 1
    fi
    if [ -e "$target" ] || [ -L "$target" ]; then
      echo "asset remained after absent-state rollback: $target" >&2
      return 1
    fi
    return 0
  else
    echo "missing rollback record for $target" >&2
    return 1
  fi
  if ! xray_validate_existing_file "$target"; then
    echo "restored asset failed validation: $target" >&2
    return 1
  fi
}

begin_asset_transaction() {
  validate_xray_install_layout || return
  if [ "$EXTERNAL_ASSET_ROLLBACK" = 1 ]; then
    # upgrade.sh has already backed up the complete rw-core/geo/ASN trees and
    # owns rollback. A nested backup would consume the same constrained disk
    # twice and could race the outer transaction's recovery policy.
    echo "using caller-owned asset rollback; skipping nested asset backup"
    INSTALL_ARMED=0
    return 0
  fi
  if ! mkdir -m 0700 "$TMP_DIR/backup"; then
    echo "failed to create asset backup directory: $TMP_DIR/backup" >&2
    return 1
  fi
  backup_asset "$XRAY_BIN" rw-core || return
  backup_asset "$GEO_DIR/geoip.dat" geoip.dat || return
  backup_asset "$GEO_DIR/geosite.dat" geosite.dat || return
  if [ -n "$ASN_SOURCE" ]; then
    backup_asset "$ASN_DB_PATH" asn-prefixes.bin || return
    ASN_TRANSACTIONAL=1
  fi
  INSTALL_ARMED=1
}

rollback_asset_transaction() {
  local failed=0
  echo "rw-core installation failed; restoring previous assets" >&2
  restore_asset rw-core "$XRAY_BIN" || failed=1
  restore_asset geoip.dat "$GEO_DIR/geoip.dat" || failed=1
  restore_asset geosite.dat "$GEO_DIR/geosite.dat" || failed=1
  if [ "$ASN_TRANSACTIONAL" -eq 1 ]; then
    restore_asset asn-prefixes.bin "$ASN_DB_PATH" || failed=1
  fi
  if [ "$failed" -ne 0 ]; then
    return 1
  fi
  INSTALL_ARMED=0
}

cleanup() {
  local status="$?" rollback_failed=0
  trap - EXIT
  if [ "$status" -ne 0 ] && [ "$INSTALL_ARMED" -eq 1 ]; then
    if ! rollback_asset_transaction; then
      echo "rw-core rollback was incomplete" >&2
      echo "rollback artifacts preserved at: $TMP_DIR" >&2
      rollback_failed=1
      status=1
    fi
  fi
  if [ "$rollback_failed" -eq 0 ] && [ -n "$TMP_DIR" ]; then
    if ! rm -rf "$TMP_DIR"; then
      echo "failed to clean installer transaction directory: $TMP_DIR" >&2
      status=1
    fi
  fi
  exit "$status"
}

select_xray_asset() {
  local pinned_sha256
  case "$(uname -m)" in
    x86_64|amd64)
      XRAY_ASSET="Xray-linux-64.zip"
      pinned_sha256="$PINNED_AMD64_SHA256"
      ;;
    aarch64|arm64)
      XRAY_ASSET="Xray-linux-arm64-v8a.zip"
      pinned_sha256="$PINNED_ARM64_SHA256"
      ;;
    *) echo "unsupported architecture: $(uname -m)" >&2; return 1 ;;
  esac

  if [ "$XRAY_CORE_VERSION" = "$PINNED_XRAY_VERSION" ]; then
    if [ -n "$XRAY_CORE_SHA256" ] && [ "${XRAY_CORE_SHA256,,}" != "${pinned_sha256,,}" ]; then
      echo "refusing SHA-256 override for pinned rw-core $PINNED_XRAY_VERSION" >&2
      return 1
    fi
    XRAY_CORE_SHA256="$pinned_sha256"
  elif [ -z "$XRAY_CORE_SHA256" ]; then
    echo "--sha256 or XRAY_CORE_SHA256 is required for unpinned rw-core $XRAY_CORE_VERSION" >&2
    return 1
  fi
}

prepare_asn_database() {
  if [ "$RNL_INSTALL_ASN" = "0" ]; then
    echo "RNL_INSTALL_ASN=0; skipping ASN database."
    return 0
  fi
  local default_source=0
  if [ -z "$ASN_DB_URL" ]; then
    ASN_DB_URL="https://github.com/${RNL_REPO}/releases/download/${RNL_TAG}/asn-prefixes.bin"
    default_source=1
  fi
  if [ -z "$ASN_DB_SHA256" ] && [ "$default_source" -eq 1 ]; then
    download_file \
      "https://github.com/${RNL_REPO}/releases/download/${RNL_TAG}/SHA256SUMS" \
      "$TMP_DIR/SHA256SUMS" 1048576
    ASN_DB_SHA256="$(awk '$2 == "asn-prefixes.bin" || $2 == "*asn-prefixes.bin" { print $1; exit }' "$TMP_DIR/SHA256SUMS")"
  fi
  if [ -z "$ASN_DB_SHA256" ]; then
    echo "ASN_DB_SHA256 is required with ASN_DB_URL" >&2
    return 1
  fi
  ASN_SOURCE="$TMP_DIR/asn-prefixes.bin"
  download_file "$ASN_DB_URL" "$ASN_SOURCE" "$XRAY_ASN_MAX_BYTES"
  verify_sha256 "$ASN_SOURCE" "$ASN_DB_SHA256"
  if [ "$(od -An -tx1 -N8 "$ASN_SOURCE" | tr -d ' \n')" != "525741534e444201" ]; then
    echo "ASN database has invalid RWASNDB header" >&2
    return 1
  fi
}

# Pure helper tests source this file without performing privileged work.
if [ "${RNL_INSTALL_XRAY_LIBRARY_ONLY:-0}" = 1 ]; then
  # shellcheck disable=SC2317
  return 0 2>/dev/null || exit 0
fi

acquire_xray_installer_lock() {
  require_root
  if [ "$DRY_RUN" -eq 0 ]; then
    installer_acquire_lock || return
  fi
}

acquire_xray_installer_lock || exit $?
case "$EXTERNAL_ASSET_ROLLBACK" in
  0|1) ;;
  *) echo "RNL_EXTERNAL_ASSET_ROLLBACK must be 0 or 1" >&2; exit 2 ;;
esac
case "$RNL_INSTALL_ASN" in
  0|1) ;;
  *) echo "RNL_INSTALL_ASN must be 0 or 1" >&2; exit 2 ;;
esac
if ! [[ "$RNL_REPO" =~ ^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9][A-Za-z0-9_.-]*$ ]] \
  || ! [[ "$RNL_TAG" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]]; then
  echo "invalid RNL_REPO or RNL_TAG" >&2
  exit 2
fi
if ! [[ "$XRAY_CORE_VERSION" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]]; then
  echo "invalid rw-core release version: $XRAY_CORE_VERSION" >&2
  exit 2
fi
for key in CUSTOM_CORE_URL CUSTOM_CORE_SHA256 ASN_DB_URL ASN_DB_SHA256; do
  load_env_var "$key" "$NODE_ENV"
done
select_xray_asset
if ! [[ "$XRAY_CORE_SHA256" =~ ^[0-9a-fA-F]{64}$ ]]; then
  echo "XRAY_CORE_SHA256 must be 64 hexadecimal characters" >&2
  exit 2
fi
if [ -n "$CUSTOM_CORE_URL" ]; then
  case "$CUSTOM_CORE_URL" in https://*) ;; *) echo "CUSTOM_CORE_URL must use HTTPS" >&2; exit 2 ;; esac
  if ! [[ "$CUSTOM_CORE_SHA256" =~ ^[0-9a-fA-F]{64}$ ]]; then
    echo "CUSTOM_CORE_SHA256 is required with CUSTOM_CORE_URL" >&2
    exit 2
  fi
fi
if [ -n "$ASN_DB_URL" ]; then
  case "$ASN_DB_URL" in https://*) ;; *) echo "ASN_DB_URL must use HTTPS" >&2; exit 2 ;; esac
  if ! [[ "$ASN_DB_SHA256" =~ ^[0-9a-fA-F]{64}$ ]]; then
    echo "ASN_DB_SHA256 is required with ASN_DB_URL" >&2
    exit 2
  fi
fi

XRAY_URL="https://github.com/XTLS/Xray-core/releases/download/${XRAY_CORE_VERSION}/${XRAY_ASSET}"
if [ "$DRY_RUN" -eq 1 ]; then
  echo "[dry-run] download and verify ${XRAY_URL}"
  echo "[dry-run] install rw-core to ${XRAY_BIN} and geo assets to ${GEO_DIR}"
  if [ -n "$CUSTOM_CORE_URL" ]; then
    echo "[dry-run] replace rw-core from verified CUSTOM_CORE_URL"
  fi
  if [ "$RNL_INSTALL_ASN" != "0" ]; then
    echo "[dry-run] install verified ASN database to ${ASN_DB_PATH}"
  fi
  exit 0
fi

if ! command -v unzip >/dev/null 2>&1; then
  echo "unzip is required" >&2
  exit 1
fi
if ! command -v timeout >/dev/null 2>&1; then
  echo "timeout is required for bounded archive processing" >&2
  exit 1
fi

preflight_disk_space
TMP_DIR="$(make_temp_dir)"
trap cleanup EXIT

download_file "$XRAY_URL" "$TMP_DIR/xray.zip" "$XRAY_ARCHIVE_MAX_BYTES"
verify_sha256 "$TMP_DIR/xray.zip" "$XRAY_CORE_SHA256"
validate_zip_structure "$TMP_DIR/xray.zip"

if [ -n "$CUSTOM_CORE_URL" ]; then
  if [ -z "$CUSTOM_CORE_SHA256" ]; then
    echo "CUSTOM_CORE_SHA256 is required with CUSTOM_CORE_URL" >&2
    exit 1
  fi
  download_file "$CUSTOM_CORE_URL" "$TMP_DIR/custom-core" "$XRAY_CORE_MAX_BYTES"
  verify_sha256 "$TMP_DIR/custom-core" "$CUSTOM_CORE_SHA256"
fi
prepare_asn_database
preflight_asset_space "$TMP_DIR/xray.zip"

extract_zip_entry_limited "$TMP_DIR/xray.zip" xray "$TMP_DIR/xray" "$XRAY_CORE_MAX_BYTES"
extract_zip_entry_limited "$TMP_DIR/xray.zip" geoip.dat "$TMP_DIR/geoip.dat" "$XRAY_GEO_FILE_MAX_BYTES"
extract_zip_entry_limited "$TMP_DIR/xray.zip" geosite.dat "$TMP_DIR/geosite.dat" "$XRAY_GEO_FILE_MAX_BYTES"
if [ -f "$TMP_DIR/custom-core" ]; then
  mv "$TMP_DIR/custom-core" "$TMP_DIR/xray"
fi

chmod 0755 "$TMP_DIR/xray"
CORE_VERSION_OUTPUT="$(installer_run_without_lock "$TMP_DIR/xray" version)"
[ -n "$CORE_VERSION_OUTPUT" ] || { echo "rw-core version self-check returned no output" >&2; exit 1; }

require_install_target_stopped /usr/local/bin/remnanode-lite
require_install_target_stopped "$XRAY_BIN"
if ! begin_asset_transaction; then
  exit 1
fi
if ! atomic_install "$TMP_DIR/xray" "$XRAY_BIN" 0755; then
  exit 1
fi
if ! atomic_install "$TMP_DIR/geoip.dat" "$GEO_DIR/geoip.dat" 0644; then
  exit 1
fi
if ! atomic_install "$TMP_DIR/geosite.dat" "$GEO_DIR/geosite.dat" 0644; then
  exit 1
fi
if [ -n "$ASN_SOURCE" ]; then
  if ! atomic_install "$ASN_SOURCE" "$ASN_DB_PATH" 0644; then
    exit 1
  fi
fi
if ! installer_run_without_lock "$XRAY_BIN" version >/dev/null; then
  echo "installed rw-core failed its version self-check" >&2
  exit 1
fi
INSTALL_ARMED=0
if [ -n "$ASN_SOURCE" ]; then
  echo "ASN database installed: $ASN_DB_PATH"
fi

if [ "$XRAY_CORE_VERSION" = "$PINNED_XRAY_VERSION" ]; then
  echo "rw-core asset: ${XRAY_CORE_VERSION}@${PINNED_XRAY_COMMIT} (${XRAY_ASSET})"
else
  echo "rw-core asset: ${XRAY_CORE_VERSION} (${XRAY_ASSET})"
fi
printf '%s\n' "$CORE_VERSION_OUTPUT" | sed -n '1p'
echo "rw-core installation complete."
