// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/xrayrpc/wire/wire.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{0}
}

type TypedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypedMessage) Reset() {
	*x = TypedMessage{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypedMessage) ProtoMessage() {}

func (x *TypedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypedMessage.ProtoReflect.Descriptor instead.
func (*TypedMessage) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{1}
}

func (x *TypedMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TypedMessage) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         uint32                 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Account       *TypedMessage          `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetAccount() *TypedMessage {
	if x != nil {
		return x.Account
	}
	return nil
}

type VlessAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Flow          string                 `protobuf:"bytes,2,opt,name=flow,proto3" json:"flow,omitempty"`
	Encryption    string                 `protobuf:"bytes,3,opt,name=encryption,proto3" json:"encryption,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VlessAccount) Reset() {
	*x = VlessAccount{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VlessAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VlessAccount) ProtoMessage() {}

func (x *VlessAccount) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VlessAccount.ProtoReflect.Descriptor instead.
func (*VlessAccount) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{3}
}

func (x *VlessAccount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VlessAccount) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

func (x *VlessAccount) GetEncryption() string {
	if x != nil {
		return x.Encryption
	}
	return ""
}

type TrojanAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrojanAccount) Reset() {
	*x = TrojanAccount{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrojanAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrojanAccount) ProtoMessage() {}

func (x *TrojanAccount) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrojanAccount.ProtoReflect.Descriptor instead.
func (*TrojanAccount) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{4}
}

func (x *TrojanAccount) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ShadowsocksAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	CipherType    int32                  `protobuf:"varint,2,opt,name=cipher_type,json=cipherType,proto3" json:"cipher_type,omitempty"`
	IvCheck       bool                   `protobuf:"varint,3,opt,name=iv_check,json=ivCheck,proto3" json:"iv_check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShadowsocksAccount) Reset() {
	*x = ShadowsocksAccount{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShadowsocksAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShadowsocksAccount) ProtoMessage() {}

func (x *ShadowsocksAccount) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShadowsocksAccount.ProtoReflect.Descriptor instead.
func (*ShadowsocksAccount) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{5}
}

func (x *ShadowsocksAccount) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ShadowsocksAccount) GetCipherType() int32 {
	if x != nil {
		return x.CipherType
	}
	return 0
}

func (x *ShadowsocksAccount) GetIvCheck() bool {
	if x != nil {
		return x.IvCheck
	}
	return false
}

type Shadowsocks2022Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shadowsocks2022Account) Reset() {
	*x = Shadowsocks2022Account{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shadowsocks2022Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shadowsocks2022Account) ProtoMessage() {}

func (x *Shadowsocks2022Account) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shadowsocks2022Account.ProtoReflect.Descriptor instead.
func (*Shadowsocks2022Account) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{6}
}

func (x *Shadowsocks2022Account) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type HysteriaAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          string                 `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HysteriaAccount) Reset() {
	*x = HysteriaAccount{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HysteriaAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HysteriaAccount) ProtoMessage() {}

func (x *HysteriaAccount) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HysteriaAccount.ProtoReflect.Descriptor instead.
func (*HysteriaAccount) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{7}
}

func (x *HysteriaAccount) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

type AddUserOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserOperation) Reset() {
	*x = AddUserOperation{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserOperation) ProtoMessage() {}

func (x *AddUserOperation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserOperation.ProtoReflect.Descriptor instead.
func (*AddUserOperation) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{8}
}

func (x *AddUserOperation) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type RemoveUserOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserOperation) Reset() {
	*x = RemoveUserOperation{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserOperation) ProtoMessage() {}

func (x *RemoveUserOperation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserOperation.ProtoReflect.Descriptor instead.
func (*RemoveUserOperation) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveUserOperation) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AlterInboundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Operation     *TypedMessage          `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlterInboundRequest) Reset() {
	*x = AlterInboundRequest{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterInboundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterInboundRequest) ProtoMessage() {}

func (x *AlterInboundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterInboundRequest.ProtoReflect.Descriptor instead.
func (*AlterInboundRequest) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{10}
}

func (x *AlterInboundRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *AlterInboundRequest) GetOperation() *TypedMessage {
	if x != nil {
		return x.Operation
	}
	return nil
}

type GetInboundUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInboundUserRequest) Reset() {
	*x = GetInboundUserRequest{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInboundUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInboundUserRequest) ProtoMessage() {}

func (x *GetInboundUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInboundUserRequest.ProtoReflect.Descriptor instead.
func (*GetInboundUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{11}
}

func (x *GetInboundUserRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *GetInboundUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetInboundUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInboundUserResponse) Reset() {
	*x = GetInboundUserResponse{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInboundUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInboundUserResponse) ProtoMessage() {}

func (x *GetInboundUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInboundUserResponse.ProtoReflect.Descriptor instead.
func (*GetInboundUserResponse) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{12}
}

func (x *GetInboundUserResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetInboundUsersCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInboundUsersCountResponse) Reset() {
	*x = GetInboundUsersCountResponse{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInboundUsersCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInboundUsersCountResponse) ProtoMessage() {}

func (x *GetInboundUsersCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInboundUsersCountResponse.ProtoReflect.Descriptor instead.
func (*GetInboundUsersCountResponse) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{13}
}

func (x *GetInboundUsersCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RemoveOutboundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveOutboundRequest) Reset() {
	*x = RemoveOutboundRequest{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveOutboundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveOutboundRequest) ProtoMessage() {}

func (x *RemoveOutboundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveOutboundRequest.ProtoReflect.Descriptor instead.
func (*RemoveOutboundRequest) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveOutboundRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Reset_        bool                   `protobuf:"varint,2,opt,name=reset,proto3" json:"reset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{15}
}

func (x *GetStatsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetStatsRequest) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

type Stat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stat) Reset() {
	*x = Stat{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stat) ProtoMessage() {}

func (x *Stat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stat.ProtoReflect.Descriptor instead.
func (*Stat) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{16}
}

func (x *Stat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stat) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stat          *Stat                  `protobuf:"bytes,1,opt,name=stat,proto3" json:"stat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{17}
}

func (x *GetStatsResponse) GetStat() *Stat {
	if x != nil {
		return x.Stat
	}
	return nil
}

type QueryStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Reset_        bool                   `protobuf:"varint,2,opt,name=reset,proto3" json:"reset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStatsRequest) Reset() {
	*x = QueryStatsRequest{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStatsRequest) ProtoMessage() {}

func (x *QueryStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStatsRequest.ProtoReflect.Descriptor instead.
func (*QueryStatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{18}
}

func (x *QueryStatsRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *QueryStatsRequest) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

type QueryStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stat          []*Stat                `protobuf:"bytes,1,rep,name=stat,proto3" json:"stat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStatsResponse) Reset() {
	*x = QueryStatsResponse{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStatsResponse) ProtoMessage() {}

func (x *QueryStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStatsResponse.ProtoReflect.Descriptor instead.
func (*QueryStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{19}
}

func (x *QueryStatsResponse) GetStat() []*Stat {
	if x != nil {
		return x.Stat
	}
	return nil
}

type SysStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumGoroutine  uint32                 `protobuf:"varint,1,opt,name=num_goroutine,json=numGoroutine,proto3" json:"num_goroutine,omitempty"`
	NumGc         uint32                 `protobuf:"varint,2,opt,name=num_gc,json=numGc,proto3" json:"num_gc,omitempty"`
	Alloc         uint64                 `protobuf:"varint,3,opt,name=alloc,proto3" json:"alloc,omitempty"`
	TotalAlloc    uint64                 `protobuf:"varint,4,opt,name=total_alloc,json=totalAlloc,proto3" json:"total_alloc,omitempty"`
	Sys           uint64                 `protobuf:"varint,5,opt,name=sys,proto3" json:"sys,omitempty"`
	Mallocs       uint64                 `protobuf:"varint,6,opt,name=mallocs,proto3" json:"mallocs,omitempty"`
	Frees         uint64                 `protobuf:"varint,7,opt,name=frees,proto3" json:"frees,omitempty"`
	LiveObjects   uint64                 `protobuf:"varint,8,opt,name=live_objects,json=liveObjects,proto3" json:"live_objects,omitempty"`
	PauseTotalNs  uint64                 `protobuf:"varint,9,opt,name=pause_total_ns,json=pauseTotalNs,proto3" json:"pause_total_ns,omitempty"`
	Uptime        uint32                 `protobuf:"varint,10,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysStatsResponse) Reset() {
	*x = SysStatsResponse{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysStatsResponse) ProtoMessage() {}

func (x *SysStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysStatsResponse.ProtoReflect.Descriptor instead.
func (*SysStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{20}
}

func (x *SysStatsResponse) GetNumGoroutine() uint32 {
	if x != nil {
		return x.NumGoroutine
	}
	return 0
}

func (x *SysStatsResponse) GetNumGc() uint32 {
	if x != nil {
		return x.NumGc
	}
	return 0
}

func (x *SysStatsResponse) GetAlloc() uint64 {
	if x != nil {
		return x.Alloc
	}
	return 0
}

func (x *SysStatsResponse) GetTotalAlloc() uint64 {
	if x != nil {
		return x.TotalAlloc
	}
	return 0
}

func (x *SysStatsResponse) GetSys() uint64 {
	if x != nil {
		return x.Sys
	}
	return 0
}

func (x *SysStatsResponse) GetMallocs() uint64 {
	if x != nil {
		return x.Mallocs
	}
	return 0
}

func (x *SysStatsResponse) GetFrees() uint64 {
	if x != nil {
		return x.Frees
	}
	return 0
}

func (x *SysStatsResponse) GetLiveObjects() uint64 {
	if x != nil {
		return x.LiveObjects
	}
	return 0
}

func (x *SysStatsResponse) GetPauseTotalNs() uint64 {
	if x != nil {
		return x.PauseTotalNs
	}
	return 0
}

func (x *SysStatsResponse) GetUptime() uint32 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

type GetStatsOnlineIpListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ips           map[string]int64       `protobuf:"bytes,2,rep,name=ips,proto3" json:"ips,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsOnlineIpListResponse) Reset() {
	*x = GetStatsOnlineIpListResponse{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsOnlineIpListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsOnlineIpListResponse) ProtoMessage() {}

func (x *GetStatsOnlineIpListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsOnlineIpListResponse.ProtoReflect.Descriptor instead.
func (*GetStatsOnlineIpListResponse) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{21}
}

func (x *GetStatsOnlineIpListResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetStatsOnlineIpListResponse) GetIps() map[string]int64 {
	if x != nil {
		return x.Ips
	}
	return nil
}

type GetAllOnlineUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []string               `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllOnlineUsersResponse) Reset() {
	*x = GetAllOnlineUsersResponse{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllOnlineUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOnlineUsersResponse) ProtoMessage() {}

func (x *GetAllOnlineUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOnlineUsersResponse.ProtoReflect.Descriptor instead.
func (*GetAllOnlineUsersResponse) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{22}
}

func (x *GetAllOnlineUsersResponse) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

// GetUsersStats is an rw-core extension used by @remnawave/xtls-sdk 0.16.0.
type OnlineIPEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	LastSeen      int64                  `protobuf:"varint,2,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineIPEntry) Reset() {
	*x = OnlineIPEntry{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineIPEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineIPEntry) ProtoMessage() {}

func (x *OnlineIPEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineIPEntry.ProtoReflect.Descriptor instead.
func (*OnlineIPEntry) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{23}
}

func (x *OnlineIPEntry) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *OnlineIPEntry) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type TrafficUserStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uplink        int64                  `protobuf:"varint,1,opt,name=uplink,proto3" json:"uplink,omitempty"`
	Downlink      int64                  `protobuf:"varint,2,opt,name=downlink,proto3" json:"downlink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficUserStat) Reset() {
	*x = TrafficUserStat{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficUserStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficUserStat) ProtoMessage() {}

func (x *TrafficUserStat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficUserStat.ProtoReflect.Descriptor instead.
func (*TrafficUserStat) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{24}
}

func (x *TrafficUserStat) GetUplink() int64 {
	if x != nil {
		return x.Uplink
	}
	return 0
}

func (x *TrafficUserStat) GetDownlink() int64 {
	if x != nil {
		return x.Downlink
	}
	return 0
}

type UserStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Ips           []*OnlineIPEntry       `protobuf:"bytes,2,rep,name=ips,proto3" json:"ips,omitempty"`
	Traffic       *TrafficUserStat       `protobuf:"bytes,3,opt,name=traffic,proto3" json:"traffic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStat) Reset() {
	*x = UserStat{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStat) ProtoMessage() {}

func (x *UserStat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStat.ProtoReflect.Descriptor instead.
func (*UserStat) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{25}
}

func (x *UserStat) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserStat) GetIps() []*OnlineIPEntry {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *UserStat) GetTraffic() *TrafficUserStat {
	if x != nil {
		return x.Traffic
	}
	return nil
}

type GetUsersStatsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncludeTraffic bool                   `protobuf:"varint,1,opt,name=include_traffic,json=includeTraffic,proto3" json:"include_traffic,omitempty"`
	Reset_         bool                   `protobuf:"varint,2,opt,name=reset,proto3" json:"reset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUsersStatsRequest) Reset() {
	*x = GetUsersStatsRequest{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersStatsRequest) ProtoMessage() {}

func (x *GetUsersStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersStatsRequest.ProtoReflect.Descriptor instead.
func (*GetUsersStatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{26}
}

func (x *GetUsersStatsRequest) GetIncludeTraffic() bool {
	if x != nil {
		return x.IncludeTraffic
	}
	return false
}

func (x *GetUsersStatsRequest) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

type GetUsersStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserStat            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersStatsResponse) Reset() {
	*x = GetUsersStatsResponse{}
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersStatsResponse) ProtoMessage() {}

func (x *GetUsersStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_xrayrpc_wire_wire_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersStatsResponse.ProtoReflect.Descriptor instead.
func (*GetUsersStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_xrayrpc_wire_wire_proto_rawDescGZIP(), []int{27}
}

func (x *GetUsersStatsResponse) GetUsers() []*UserStat {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_internal_xrayrpc_wire_wire_proto protoreflect.FileDescriptor

const file_internal_xrayrpc_wire_wire_proto_rawDesc = "" +
	"\n" +
	" internal/xrayrpc/wire/wire.proto\x12\x13remnanode.xtls.wire\"\a\n" +
	"\x05Empty\"8\n" +
	"\fTypedMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"o\n" +
	"\x04User\x12\x14\n" +
	"\x05level\x18\x01 \x01(\rR\x05level\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12;\n" +
	"\aaccount\x18\x03 \x01(\v2!.remnanode.xtls.wire.TypedMessageR\aaccount\"R\n" +
	"\fVlessAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04flow\x18\x02 \x01(\tR\x04flow\x12\x1e\n" +
	"\n" +
	"encryption\x18\x03 \x01(\tR\n" +
	"encryption\"+\n" +
	"\rTrojanAccount\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"l\n" +
	"\x12ShadowsocksAccount\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x1f\n" +
	"\vcipher_type\x18\x02 \x01(\x05R\n" +
	"cipherType\x12\x19\n" +
	"\biv_check\x18\x03 \x01(\bR\aivCheck\"*\n" +
	"\x16Shadowsocks2022Account\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"%\n" +
	"\x0fHysteriaAccount\x12\x12\n" +
	"\x04auth\x18\x01 \x01(\tR\x04auth\"A\n" +
	"\x10AddUserOperation\x12-\n" +
	"\x04user\x18\x01 \x01(\v2\x19.remnanode.xtls.wire.UserR\x04user\"+\n" +
	"\x13RemoveUserOperation\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"h\n" +
	"\x13AlterInboundRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12?\n" +
	"\toperation\x18\x02 \x01(\v2!.remnanode.xtls.wire.TypedMessageR\toperation\"?\n" +
	"\x15GetInboundUserRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"I\n" +
	"\x16GetInboundUserResponse\x12/\n" +
	"\x05users\x18\x01 \x03(\v2\x19.remnanode.xtls.wire.UserR\x05users\"4\n" +
	"\x1cGetInboundUsersCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\")\n" +
	"\x15RemoveOutboundRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\";\n" +
	"\x0fGetStatsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05reset\x18\x02 \x01(\bR\x05reset\"0\n" +
	"\x04Stat\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"A\n" +
	"\x10GetStatsResponse\x12-\n" +
	"\x04stat\x18\x01 \x01(\v2\x19.remnanode.xtls.wire.StatR\x04stat\"C\n" +
	"\x11QueryStatsRequest\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12\x14\n" +
	"\x05reset\x18\x02 \x01(\bR\x05reset\"C\n" +
	"\x12QueryStatsResponse\x12-\n" +
	"\x04stat\x18\x01 \x03(\v2\x19.remnanode.xtls.wire.StatR\x04stat\"\xa8\x02\n" +
	"\x10SysStatsResponse\x12#\n" +
	"\rnum_goroutine\x18\x01 \x01(\rR\fnumGoroutine\x12\x15\n" +
	"\x06num_gc\x18\x02 \x01(\rR\x05numGc\x12\x14\n" +
	"\x05alloc\x18\x03 \x01(\x04R\x05alloc\x12\x1f\n" +
	"\vtotal_alloc\x18\x04 \x01(\x04R\n" +
	"totalAlloc\x12\x10\n" +
	"\x03sys\x18\x05 \x01(\x04R\x03sys\x12\x18\n" +
	"\amallocs\x18\x06 \x01(\x04R\amallocs\x12\x14\n" +
	"\x05frees\x18\a \x01(\x04R\x05frees\x12!\n" +
	"\flive_objects\x18\b \x01(\x04R\vliveObjects\x12$\n" +
	"\x0epause_total_ns\x18\t \x01(\x04R\fpauseTotalNs\x12\x16\n" +
	"\x06uptime\x18\n" +
	" \x01(\rR\x06uptime\"\xb8\x01\n" +
	"\x1cGetStatsOnlineIpListResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12L\n" +
	"\x03ips\x18\x02 \x03(\v2:.remnanode.xtls.wire.GetStatsOnlineIpListResponse.IpsEntryR\x03ips\x1a6\n" +
	"\bIpsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"1\n" +
	"\x19GetAllOnlineUsersResponse\x12\x14\n" +
	"\x05users\x18\x01 \x03(\tR\x05users\"<\n" +
	"\rOnlineIPEntry\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1b\n" +
	"\tlast_seen\x18\x02 \x01(\x03R\blastSeen\"E\n" +
	"\x0fTrafficUserStat\x12\x16\n" +
	"\x06uplink\x18\x01 \x01(\x03R\x06uplink\x12\x1a\n" +
	"\bdownlink\x18\x02 \x01(\x03R\bdownlink\"\x96\x01\n" +
	"\bUserStat\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x124\n" +
	"\x03ips\x18\x02 \x03(\v2\".remnanode.xtls.wire.OnlineIPEntryR\x03ips\x12>\n" +
	"\atraffic\x18\x03 \x01(\v2$.remnanode.xtls.wire.TrafficUserStatR\atraffic\"U\n" +
	"\x14GetUsersStatsRequest\x12'\n" +
	"\x0finclude_traffic\x18\x01 \x01(\bR\x0eincludeTraffic\x12\x14\n" +
	"\x05reset\x18\x02 \x01(\bR\x05reset\"L\n" +
	"\x15GetUsersStatsResponse\x123\n" +
	"\x05users\x18\x01 \x03(\v2\x1d.remnanode.xtls.wire.UserStatR\x05usersB9Z7github.com/luxiaba/remnanode-lite/internal/xrayrpc/wireb\x06proto3"

var (
	file_internal_xrayrpc_wire_wire_proto_rawDescOnce sync.Once
	file_internal_xrayrpc_wire_wire_proto_rawDescData []byte
)

func file_internal_xrayrpc_wire_wire_proto_rawDescGZIP() []byte {
	file_internal_xrayrpc_wire_wire_proto_rawDescOnce.Do(func() {
		file_internal_xrayrpc_wire_wire_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_xrayrpc_wire_wire_proto_rawDesc), len(file_internal_xrayrpc_wire_wire_proto_rawDesc)))
	})
	return file_internal_xrayrpc_wire_wire_proto_rawDescData
}

var file_internal_xrayrpc_wire_wire_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_internal_xrayrpc_wire_wire_proto_goTypes = []any{
	(*Empty)(nil),                        // 0: remnanode.xtls.wire.Empty
	(*TypedMessage)(nil),                 // 1: remnanode.xtls.wire.TypedMessage
	(*User)(nil),                         // 2: remnanode.xtls.wire.User
	(*VlessAccount)(nil),                 // 3: remnanode.xtls.wire.VlessAccount
	(*TrojanAccount)(nil),                // 4: remnanode.xtls.wire.TrojanAccount
	(*ShadowsocksAccount)(nil),           // 5: remnanode.xtls.wire.ShadowsocksAccount
	(*Shadowsocks2022Account)(nil),       // 6: remnanode.xtls.wire.Shadowsocks2022Account
	(*HysteriaAccount)(nil),              // 7: remnanode.xtls.wire.HysteriaAccount
	(*AddUserOperation)(nil),             // 8: remnanode.xtls.wire.AddUserOperation
	(*RemoveUserOperation)(nil),          // 9: remnanode.xtls.wire.RemoveUserOperation
	(*AlterInboundRequest)(nil),          // 10: remnanode.xtls.wire.AlterInboundRequest
	(*GetInboundUserRequest)(nil),        // 11: remnanode.xtls.wire.GetInboundUserRequest
	(*GetInboundUserResponse)(nil),       // 12: remnanode.xtls.wire.GetInboundUserResponse
	(*GetInboundUsersCountResponse)(nil), // 13: remnanode.xtls.wire.GetInboundUsersCountResponse
	(*RemoveOutboundRequest)(nil),        // 14: remnanode.xtls.wire.RemoveOutboundRequest
	(*GetStatsRequest)(nil),              // 15: remnanode.xtls.wire.GetStatsRequest
	(*Stat)(nil),                         // 16: remnanode.xtls.wire.Stat
	(*GetStatsResponse)(nil),             // 17: remnanode.xtls.wire.GetStatsResponse
	(*QueryStatsRequest)(nil),            // 18: remnanode.xtls.wire.QueryStatsRequest
	(*QueryStatsResponse)(nil),           // 19: remnanode.xtls.wire.QueryStatsResponse
	(*SysStatsResponse)(nil),             // 20: remnanode.xtls.wire.SysStatsResponse
	(*GetStatsOnlineIpListResponse)(nil), // 21: remnanode.xtls.wire.GetStatsOnlineIpListResponse
	(*GetAllOnlineUsersResponse)(nil),    // 22: remnanode.xtls.wire.GetAllOnlineUsersResponse
	(*OnlineIPEntry)(nil),                // 23: remnanode.xtls.wire.OnlineIPEntry
	(*TrafficUserStat)(nil),              // 24: remnanode.xtls.wire.TrafficUserStat
	(*UserStat)(nil),                     // 25: remnanode.xtls.wire.UserStat
	(*GetUsersStatsRequest)(nil),         // 26: remnanode.xtls.wire.GetUsersStatsRequest
	(*GetUsersStatsResponse)(nil),        // 27: remnanode.xtls.wire.GetUsersStatsResponse
	nil,                                  // 28: remnanode.xtls.wire.GetStatsOnlineIpListResponse.IpsEntry
}
var file_internal_xrayrpc_wire_wire_proto_depIdxs = []int32{
	1,  // 0: remnanode.xtls.wire.User.account:type_name -> remnanode.xtls.wire.TypedMessage
	2,  // 1: remnanode.xtls.wire.AddUserOperation.user:type_name -> remnanode.xtls.wire.User
	1,  // 2: remnanode.xtls.wire.AlterInboundRequest.operation:type_name -> remnanode.xtls.wire.TypedMessage
	2,  // 3: remnanode.xtls.wire.GetInboundUserResponse.users:type_name -> remnanode.xtls.wire.User
	16, // 4: remnanode.xtls.wire.GetStatsResponse.stat:type_name -> remnanode.xtls.wire.Stat
	16, // 5: remnanode.xtls.wire.QueryStatsResponse.stat:type_name -> remnanode.xtls.wire.Stat
	28, // 6: remnanode.xtls.wire.GetStatsOnlineIpListResponse.ips:type_name -> remnanode.xtls.wire.GetStatsOnlineIpListResponse.IpsEntry
	23, // 7: remnanode.xtls.wire.UserStat.ips:type_name -> remnanode.xtls.wire.OnlineIPEntry
	24, // 8: remnanode.xtls.wire.UserStat.traffic:type_name -> remnanode.xtls.wire.TrafficUserStat
	25, // 9: remnanode.xtls.wire.GetUsersStatsResponse.users:type_name -> remnanode.xtls.wire.UserStat
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_xrayrpc_wire_wire_proto_init() }
func file_internal_xrayrpc_wire_wire_proto_init() {
	if File_internal_xrayrpc_wire_wire_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_xrayrpc_wire_wire_proto_rawDesc), len(file_internal_xrayrpc_wire_wire_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_xrayrpc_wire_wire_proto_goTypes,
		DependencyIndexes: file_internal_xrayrpc_wire_wire_proto_depIdxs,
		MessageInfos:      file_internal_xrayrpc_wire_wire_proto_msgTypes,
	}.Build()
	File_internal_xrayrpc_wire_wire_proto = out.File
	file_internal_xrayrpc_wire_wire_proto_goTypes = nil
	file_internal_xrayrpc_wire_wire_proto_depIdxs = nil
}
